import{useState,useEffect,useMemo,useCallback}from"react";
const C={bg:"#F0EDE4",cd:"#FFFDF8",p:"#2D6A4F",pd:"#1B4332",pl:"#D8F3DC",a:"#F4845F",al:"#FDDDD2",t:"#1B1B1E",m:"#7C7C7C",b:"#DDD8CE",o:"#CAF0F8",od:"#0077B6",w:"#FFF8F0",r:"#EF4444",g:"#059669"};
const TG={fenced:"🔒 Fenced",shade:"🌳 Shaded",splashpad:"💦 Splash Pad",restrooms:"🚻 Restrooms",toddler:"👶 Toddler",parking:"🅿️ Parking",dogs:"🐕 Dogs OK",food:"🍔 Food",stroller:"🛤️ Strollers",inclusive:"♿ Inclusive",swings:"🎪 Swings",picnic:"🧺 Picnic"};
const AR=["All","Downtown","West Ashley","Mt. Pleasant","North Charleston","James Island","Johns Island","Daniel Island","Sullivan's Island","Folly Beach","Isle of Palms","Kiawah Island"];
const RC=[{k:"overall",l:"Overall",i:"⭐"},{k:"shade",l:"Shade",i:"🌳"},{k:"equipment",l:"Equipment",i:"🎠"},{k:"cleanliness",l:"Clean",i:"✨"},{k:"bugs",l:"Low(er) Bugs",i:"🦟"},{k:"safety",l:"Safety",i:"🛡️"},{k:"toddlerFriendly",l:"Tot-Friendly",i:"👶"},{k:"nearbyFood",l:"Food Nearby",i:"🍕"}];
const Ph=({e,h,ht=120})=><div style={{width:"100%",height:ht,background:`linear-gradient(135deg,hsl(${h},42%,84%),hsl(${(h+40)%360},36%,77%))`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:ht>150?80:50}}>{e}</div>;
const D=[
{id:1,n:"Bridgepoint Ecological Park",a:"West Ashley",ad:"West Ashley, SC 29407",e:"🌿",h:110,t:["fenced","stroller"],r:{overall:0,shade:0,equipment:0,cleanliness:0,bugs:0,safety:0,toddlerFriendly:0,nearbyFood:0},d:"Brand new March 2026! Resilient design, audio tours via QR codes.",p:null,f:[]},
{id:2,n:"Randolph Park",a:"West Ashley",ad:"Randolph Park, West Ashley, SC",e:"🌳",h:80,t:["shade","toddler","picnic"],r:{overall:4.0,shade:5,equipment:3.5,cleanliness:4,bugs:3,safety:4,toddlerFriendly:4.5,nearbyFood:3},d:"Heavy oak shade, fireplace shelter. Toddler hub.",p:null,f:[]},
{id:3,n:"West Ashley Park",a:"West Ashley",ad:"3601 Mary Ader Dr, Charleston, SC 29414",e:"🎣",h:90,t:["shade","restrooms","toddler","parking","dogs","stroller","swings","picnic"],r:{overall:4.5,shade:4,equipment:4.5,cleanliness:4,bugs:3,safety:4,toddlerFriendly:4.5,nearbyFood:3},d:"260 acres — TWO playgrounds, fishing, disc golf, trails.",p:null,f:[{n:"Swig & Swine",t:"BBQ",d:"Kid-friendly BBQ.",a:"1217 Savannah Hwy"},{n:"Boxcar Betty's",t:"Sandwiches",d:"Fried chicken.",a:"1922 Savannah Hwy"}]},
{id:4,n:"Mulberry Park",a:"West Ashley",ad:"Mulberry Park, West Ashley, SC",e:"🍊",h:50,t:["shade","stroller"],r:{overall:3.8,shade:4,equipment:3.5,cleanliness:4,bugs:3,safety:4,toddlerFriendly:3.5,nearbyFood:2},d:"Food Forest — citrus and herbs!",p:null,f:[]},
{id:5,n:"Mary Utsey (Orange Grove)",a:"West Ashley",ad:"1350 Orange Grove Rd, Charleston",e:"🎡",h:45,t:["inclusive","toddler","parking","swings"],r:{overall:4.1,shade:3,equipment:4,cleanliness:4,bugs:3,safety:4,toddlerFriendly:4.5,nearbyFood:3},d:"Sensory-friendly — roller slides, expression swings.",p:null,f:[]},
{id:6,n:"Bees Landing Rec Center",a:"West Ashley",ad:"Bees Landing, West Ashley, SC",e:"🐝",h:55,t:["restrooms","toddler","parking","dogs"],r:{overall:4.2,shade:3.5,equipment:4.5,cleanliness:4.5,bugs:3,safety:4.5,toddlerFriendly:4,nearbyFood:3},d:"Modern equipment, rubberized flooring, dog park.",p:null,f:[]},
{id:7,n:"Lenevar Playground",a:"West Ashley",ad:"Lenevar Park, West Ashley, SC",e:"🎾",h:65,t:["toddler","swings"],r:{overall:3.7,shade:3,equipment:3.5,cleanliness:3.5,bugs:3,safety:3.5,toddlerFriendly:3.5,nearbyFood:2.5},d:"Renovated — tennis courts, exercise stations. No bathrooms.",p:null,f:[]},
{id:8,n:"Parkshore Park",a:"West Ashley",ad:"Parkshore Park, West Ashley, SC",e:"🌲",h:130,t:["shade","stroller","parking"],r:{overall:3.9,shade:5,equipment:3,cleanliness:4,bugs:2.5,safety:4,toddlerFriendly:3,nearbyFood:2},d:"10-acre wooded park, 0.5-mile trail.",p:null,f:[]},
{id:9,n:"Ackerman Park",a:"West Ashley",ad:"55 Sycamore Ave, Charleston, SC 29407",e:"🛹",h:60,t:["toddler","dogs","parking","swings","fenced"],r:{overall:4.2,shade:2.5,equipment:4,cleanliness:4,bugs:3,safety:4,toddlerFriendly:4,nearbyFood:3.5},d:"Fenced, next to skate park. Dog park. Limited shade!",p:null,f:[{n:"Edmund's Oast",t:"Brewery",d:"Lawn for kids.",a:"1505 King St Ext"}]},
{id:10,n:"Magnolia Children's Garden",a:"West Ashley",ad:"3550 Ashley River Rd, Charleston",e:"🧚",h:300,t:["shade","restrooms","stroller","parking"],r:{overall:4.7,shade:5,equipment:4,cleanliness:5,bugs:2.5,safety:4.5,toddlerFriendly:5,nearbyFood:2},d:"Fairy garden — gnomes, storybook walk.",p:null,f:[]},
{id:11,n:"James Island County Park",a:"James Island",ad:"871 Riverland Dr, Charleston, SC 29412",e:"🎄",h:30,t:["shade","restrooms","splashpad","toddler","parking","dogs","stroller","swings","picnic"],r:{overall:4.8,shade:4.5,equipment:4.5,cleanliness:5,bugs:3,safety:5,toddlerFriendly:5,nearbyFood:2.5},d:"Massive — splash pad, climbing wall, disc golf, Holiday Lights.",p:"gold",f:[{n:"Kickin' Chicken",t:"Chicken",d:"Kids love tenders.",a:"1626 Camp Rd"}]},
{id:12,n:"Plymouth Park",a:"James Island",ad:"1309 Ft Johnson Rd, Charleston",e:"🌊",h:190,t:["shade","toddler","swings","picnic"],r:{overall:4.2,shade:5,equipment:3.5,cleanliness:3.5,bugs:3,safety:4,toddlerFriendly:4,nearbyFood:3},d:"Oak shade, Wappoo Creek. Fire station!",p:null,f:[]},
{id:13,n:"JI Recreation Complex",a:"James Island",ad:"JI Rec, Charleston, SC 29412",e:"⚽",h:75,t:["restrooms","toddler","parking","swings"],r:{overall:4.0,shade:3,equipment:4,cleanliness:4,bugs:3,safety:4,toddlerFriendly:4,nearbyFood:3},d:"Playground, sports fields, pool.",p:null,f:[]},
{id:14,n:"Wave Watch Playground",a:"Folly Beach",ad:"500 W Cooper Ave, Folly Beach",e:"🌊",h:195,t:["fenced","shade","restrooms","toddler","parking","swings"],r:{overall:4.3,shade:4,equipment:4,cleanliness:4,bugs:3,safety:4.5,toddlerFriendly:4.5,nearbyFood:4},d:"Fully fenced! Oceanfront murals, slides, swings, gazebo, Little Library. 7:30am–8:30pm.",p:null,f:[{n:"Lost Dog Café",t:"Café",d:"Wraps, salads.",a:"106 W Huron Ave"}]},
{id:15,n:"Pirates Cove",a:"Folly Beach",ad:"Pirates Cove, Folly Beach, SC",e:"🏴‍☠️",h:180,t:["shade","restrooms","toddler","parking","swings","picnic"],r:{overall:4.4,shade:4,equipment:4,cleanliness:4,bugs:3,safety:4,toddlerFriendly:4,nearbyFood:4.5},d:"Pirate ship, lighthouse slide, gazebo, skate park.",p:null,f:[]},
{id:16,n:"Johns Island County Park",a:"Johns Island",ad:"Johns Island County Park, SC",e:"🏹",h:100,t:["shade","restrooms","parking","stroller"],r:{overall:4.1,shade:4,equipment:3.5,cleanliness:4,bugs:2.5,safety:4,toddlerFriendly:3,nearbyFood:2},d:"Nature trails, archery range, climbing.",p:"gold",f:[]},
{id:17,n:"Johns Island Park",a:"Johns Island",ad:"Johns Island Park, SC",e:"🏃",h:85,t:["toddler","parking","swings","restrooms"],r:{overall:3.9,shade:3,equipment:3.5,cleanliness:4,bugs:3,safety:4,toddlerFriendly:4,nearbyFood:2.5},d:"'Tot Lot' and sports fields.",p:null,f:[]},
{id:18,n:"Stono River County Park",a:"Johns Island",ad:"Stono River County Park, SC",e:"🦢",h:140,t:["shade","parking","stroller"],r:{overall:3.8,shade:4.5,equipment:2.5,cleanliness:4,bugs:2.5,safety:4,toddlerFriendly:2.5,nearbyFood:2},d:"Marsh boardwalks, scenic trails.",p:"gold",f:[]},
{id:19,n:"Hampton Park",a:"Downtown",ad:"30 Mary Murray Dr, Charleston, SC 29403",e:"🦆",h:120,t:["shade","stroller","toddler","dogs","picnic"],r:{overall:4.6,shade:5,equipment:4,cleanliness:4.5,bugs:3,safety:4.5,toddlerFriendly:5,nearbyFood:3.5},d:"Historic — duck pond, trail loops.",p:null,f:[{n:"Basic Kitchen",t:"Healthy",d:"Plant-based, salmon.",a:"82 Wentworth St"},{n:"Rodney Scott's",t:"BBQ",d:"Whole-hog.",a:"1011 King St"}]},
{id:20,n:"Gadsdenboro Park",a:"Downtown",ad:"30 Concord St, Charleston, SC 29401",e:"⚓",h:210,t:["shade","stroller","toddler","food","swings"],r:{overall:4.3,shade:3.5,equipment:4,cleanliness:4,bugs:3.5,safety:4,toddlerFriendly:4,nearbyFood:5},d:"Net-climbing near Aquarium. Ravenel views.",p:null,f:[{n:"Harken Café",t:"Bakery",d:"Pastries.",a:"62 Queen St"}]},
{id:21,n:"Hazel Parker",a:"Downtown",ad:"70 East Bay St, Charleston, SC 29401",e:"🎾",h:170,t:["shade","restrooms","toddler","dogs","swings","stroller"],r:{overall:4.5,shade:4,equipment:4,cleanliness:4,bugs:3,safety:4,toddlerFriendly:4.5,nearbyFood:5},d:"Waterfront, oak shade, tennis, near Battery.",p:null,f:[{n:"Fleet Landing",t:"Seafood",d:"Waterfront.",a:"186 Concord St"}]},
{id:22,n:"Moultrie Playground",a:"Downtown",ad:"Moultrie Playground, Charleston",e:"🧗",h:260,t:["toddler","swings","inclusive"],r:{overall:4.2,shade:3,equipment:4.5,cleanliness:4,bugs:3,safety:4,toddlerFriendly:4,nearbyFood:4},d:"Net structures, rubber surface, pickleball.",p:null,f:[]},
{id:23,n:"Brittlebank Park",a:"Downtown",ad:"Brittlebank Park, Charleston",e:"♿",h:200,t:["inclusive","stroller","restrooms","parking"],r:{overall:4.1,shade:3,equipment:3.5,cleanliness:4,bugs:3,safety:4,toddlerFriendly:3.5,nearbyFood:3.5},d:"Ashley River waterfront, inclusive ramps.",p:null,f:[]},
{id:24,n:"Park Circle",a:"North Charleston",ad:"4800 Park Circle, N. Charleston, SC 29405",e:"🏰",h:150,t:["fenced","shade","inclusive","restrooms","toddler","parking","swings","picnic"],r:{overall:4.9,shade:5,equipment:5,cleanliness:4.5,bugs:3.5,safety:5,toddlerFriendly:5,nearbyFood:4.5},d:"World's Largest Inclusive — 55K sq ft! Ninja, zip lines.",p:null,f:[{n:"EVO Bakery",t:"Pizza",d:"Pizzas, patio.",a:"1075 E Montague"},{n:"Jackrabbit Filly",t:"Farm-table",d:"Veggie-forward.",a:"4628 Spruill Ave"}]},
{id:25,n:"Wannamaker County Park",a:"North Charleston",ad:"8888 University Blvd, N. Charleston",e:"🛹",h:250,t:["shade","restrooms","splashpad","toddler","parking","stroller","swings","picnic"],r:{overall:4.6,shade:5,equipment:4.5,cleanliness:4.5,bugs:3,safety:4.5,toddlerFriendly:4.5,nearbyFood:2},d:"Tot Lot + Fun Lot, splash pad, stroller trails.",p:"gold",f:[]},
{id:26,n:"Palmetto Islands",a:"Mt. Pleasant",ad:"444 Needlerush Pkwy, Mt. Pleasant",e:"🗼",h:140,t:["shade","restrooms","toddler","parking","picnic","swings"],r:{overall:4.7,shade:5,equipment:5,cleanliness:4.5,bugs:2.5,safety:4.5,toddlerFriendly:4.5,nearbyFood:2},d:"'Big Toy' — 50-ft tower with slides.",p:"gold",f:[{n:"Lillie Fuel",t:"Healthy",d:"Order ahead.",a:"426 W Coleman Blvd"}]},
{id:27,n:"Mt. Pleasant Waterfront",a:"Mt. Pleasant",ad:"99 Harry M Hallman Jr Blvd, Mt. Pleasant",e:"🌉",h:200,t:["shade","splashpad","restrooms","toddler","parking","food","stroller","swings","picnic"],r:{overall:4.8,shade:4,equipment:4.5,cleanliness:4.5,bugs:3,safety:4.5,toddlerFriendly:5,nearbyFood:4},d:"Nautical under Ravenel Bridge. Dolphins!",p:null,f:[{n:"Page's Okra",t:"Lowcountry",d:"Great portions.",a:"302 Coleman Blvd"},{n:"Coastal Crust",t:"Pizza",d:"Truck playground!",a:"219 Simmons St"}]},
{id:28,n:"Alhambra Playground",a:"Mt. Pleasant",ad:"Alhambra Hall, Mt. Pleasant",e:"🌳",h:115,t:["shade","toddler","inclusive"],r:{overall:4.1,shade:5,equipment:3.5,cleanliness:4,bugs:3,safety:4,toddlerFriendly:4,nearbyFood:3},d:"Massive oaks, harbor views, sensory-friendly.",p:null,f:[]},
{id:29,n:"Noah's Ark (LifePark)",a:"Mt. Pleasant",ad:"LifePark, Mt. Pleasant",e:"🚢",h:35,t:["fenced","toddler","swings","picnic"],r:{overall:4.3,shade:3.5,equipment:4,cleanliness:4,bugs:3,safety:4.5,toddlerFriendly:4.5,nearbyFood:3},d:"Giant wooden ark, fenced, huge lawn.",p:null,f:[]},
{id:30,n:"IOP County Park",a:"Isle of Palms",ad:"14th Ave, Isle of Palms",e:"🏖️",h:185,t:["restrooms","toddler","parking","swings"],r:{overall:4.3,shade:3,equipment:4,cleanliness:4,bugs:3,safety:4,toddlerFriendly:4,nearbyFood:3.5},d:"Oceanfront, sand play. Right at beach!",p:"gold",f:[]},
{id:31,n:"IOP Recreation",a:"Isle of Palms",ad:"IOP Rec, Isle of Palms",e:"🎪",h:175,t:["toddler","swings","restrooms"],r:{overall:4.2,shade:3,equipment:4.5,cleanliness:4.5,bugs:3,safety:4.5,toddlerFriendly:4,nearbyFood:3},d:"Modern structures, rubber floor, near beach.",p:null,f:[]},
{id:32,n:"Governor's Park",a:"Daniel Island",ad:"Governor's Park, Daniel Island",e:"🏃",h:220,t:["shade","restrooms","parking","stroller","swings"],r:{overall:4.4,shade:4,equipment:4.5,cleanliness:4.5,bugs:3,safety:4.5,toddlerFriendly:4,nearbyFood:3.5},d:"Zip line! Waterfront trails.",p:null,f:[{n:"King's Tide",t:"Waterfront",d:"For families.",a:"1959 Daniel Island Dr"}]},
{id:33,n:"Pirate Cove (Smythe)",a:"Daniel Island",ad:"Smythe Park, Daniel Island",e:"🏴‍☠️",h:160,t:["shade","toddler","swings","picnic"],r:{overall:4.3,shade:4,equipment:4,cleanliness:4.5,bugs:3,safety:4.5,toddlerFriendly:4.5,nearbyFood:3},d:"Pirate ship over the pond.",p:null,f:[]},
{id:34,n:"Beachwalker Park",a:"Kiawah Island",ad:"8 Beachwalker Dr, Kiawah",e:"🐚",h:165,t:["parking","stroller"],r:{overall:3.8,shade:2.5,equipment:3,cleanliness:4,bugs:3,safety:4,toddlerFriendly:3,nearbyFood:1.5},d:"Seasonal beach park, boardwalk play.",p:"gold",f:[]},
{id:35,n:"Sullivan's Island Park",a:"Sullivan's Island",ad:"2056 Middle St, Sullivan's Island",e:"🐚",h:155,t:["shade","toddler","food","swings"],r:{overall:4.3,shade:4,equipment:4,cleanliness:4.5,bugs:3,safety:4.5,toddlerFriendly:4,nearbyFood:4.5},d:"Oak canopy. Beach, restaurants, Fort Moultrie.",p:null,f:[{n:"Obstinate Daughter",t:"Italian",d:"Pizza + Beardcats!",a:"2063 Middle St"},{n:"Home Team BBQ",t:"BBQ",d:"Corn hole, $2.75 kids.",a:"2209 Middle St"}]},
];
const AC=[{n:"SC Aquarium",ad:"100 Aquarium Wharf",ic:"🐠",ur:"https://scaquarium.org",hr:"Daily 9–5",co:"~$30-45",ds:"5,000+ animals, touch tanks, sea turtles."},{n:"Children's Museum",ad:"25 Ann St",ic:"🎨",ur:"https://explorecml.org",hr:"M-Sa 10–5, Su 12–5",co:"$15/$13/$3",ds:"Pirate ship, art room. 2–3 hrs."},{n:"Charles Towne Landing",ad:"1500 Old Towne Rd",ic:"🦬",ur:"https://southcarolinaparks.com/charles-towne-landing",hr:"Daily 9–5",co:"$10/$6/$0",ds:"Zoo, ship, 80 acres."},{n:"Pack Athletics WA",ad:"1012 St Andrews Blvd",ic:"🤸",ur:"https://www.allaboutthepack.com/west-ashley",hr:"Varies",co:"Varies",ds:"Cheer, tumbling, ninja, tot gym."},{n:"Pack Athletics MP",ad:"1172 US Hwy 41",ic:"🤸",ur:"https://www.allaboutthepack.com",hr:"Varies",co:"Varies",ds:"Tumbling, cheer, open gym."},{n:"Whirlin' Waters",ad:"8888 University Blvd",ic:"🌊",ur:"https://www.ccprc.com",hr:"May–Sep",co:"Splash Pass",ds:"Slides, lazy river."},{n:"Splash Zone",ad:"871 Riverland Dr",ic:"🦜",ur:"https://www.ccprc.com",hr:"May–Sep",co:"Splash Pass",ds:"Rainforest-themed."},{n:"SK8 Charleston",ad:"8888 University Blvd",ic:"🛹",ur:"https://www.ccprc.com",hr:"ccprc.com",co:"$40/yr",ds:"32K sq ft skatepark."},{n:"Patriots Point",ad:"40 Patriots Point Rd",ic:"🚢",ur:"https://www.patriotspoint.org",hr:"Daily 9–5",co:"~$30/$20",ds:"USS Yorktown, sub."},{n:"Magnolia Plantation",ad:"3550 Ashley River Rd",ic:"🧚",ur:"https://www.magnoliaplantation.com",hr:"Daily 9–4:30",co:"~$25/$15",ds:"Fairy garden, train, zoo."},{n:"Middleton Place",ad:"4300 Ashley River Rd",ic:"🐴",ur:"https://www.middletonplace.org",hr:"Daily 9–5",co:"~$29/$18",ds:"Farm, stableyards, trails."}];
const BH=[{n:"Isle of Palms County Park",ad:"14th Ave, IOP",ps:"gold",ds:"Best family beach — playground, snack shack, lifeguards.",tp:["🕐 Before 9:30am Saturdays","💰 $10 or Gold Pass","🛝 Playground at entrance","♿ Beach wheelchair","🍔 Snack shack"]},{n:"Folly Beach County Park",ad:"1010 W Ashley Ave, Folly",ps:"gold",ds:"Lifeguards, showers, rentals. Gentle waves.",tp:["🕐 Before 10am weekends","💰 $10 or Gold Pass","⛱️ Chair rentals","🚿 Rinse stations","☀️ Bring tent"]},{n:"Kiawah Beachwalker",ad:"8 Beachwalker Dr, Kiawah",ps:"gold",ds:"Pristine, quiet, natural dunes.",tp:["🕐 45 min drive","💰 $10 or Gold Pass","🧊 Pack cooler","🌿 Boardwalk dunes","📅 Check hours"]},{n:"Sullivan's Island",ad:"Sullivan's Island, SC",ps:"free",ds:"Free parking. No facilities. Walk to restaurants.",tp:["✨ Free!","🚫 No lifeguards","💧 Bring everything","🍽️ Walk to restaurants","👥 Less crowded"]},{n:"Edisto Beach SP",ad:"8377 State Cabin Rd, Edisto",ps:"state",ds:"Quiet ~1 hr. Forest trails, camping.",tp:["🕐 1 hour","💰 $8/$5 or State Pass","🏕️ Beachfront camping","🌲 4-mi trail","🔬 Nature center"]},{n:"Hunting Island SP",ad:"2555 Sea Island Pkwy",ps:"state",ds:"5 mi driftwood beach. ~2 hrs.",tp:["🕐 2 hours","💰 $8/$5 or State Pass","🪵 Driftwood beach","🧺 Pack lunch","🐊 Watch for gators"]}];
const LB=[{n:"Main Library",ad:"68 Calhoun St",nt:"Storytimes & crafts."},{n:"Bees Ferry",ad:"3689 Bees Ferry Rd",nt:"Gated outdoor play!"},{n:"Mt. Pleasant",ad:"1133 Mathis Ferry Rd",nt:"Baby storytimes."},{n:"Otranto Road",ad:"2261 Otranto Rd",nt:"Weekly storytimes."},{n:"James Island",ad:"1248 Camp Rd",nt:"Toddler storytimes."},{n:"John's Island",ad:"3531 Maybank Hwy",nt:"Summer reading."},{n:"Hurd/St. Andrews",ad:"1735 N Woodmere Dr",nt:"Newly renovated!"},{n:"Dorchester Rd",ad:"6325 Dorchester Rd",nt:"30+ Storytime Kits."}];
const CM=[{h:"@jetsetchristina",nm:"JetsetChristina",u:"https://www.instagram.com/jetsetchristina/",ds:"Luxury travel & family · 116K",c:"#E8D5B7",i:"JC"},{h:"@chswithkids",nm:"CHS With Kids",u:"https://www.instagram.com/chswithkids/",ds:"Parent recs & weekends",c:"#B5EAD7",i:"CK"},{h:"@charlestontoddlers",nm:"Charleston Toddlers",u:"https://www.instagram.com/charlestontoddlers/",ds:"Toddler activities & reviews",c:"#C7CEEA",i:"CT"},{h:"@littlesinthelowcountry",nm:"Littles in the Lowcountry",u:"https://www.instagram.com/littlesinthelowcountry/",ds:"Adventures & gems",c:"#FFD6E0",i:"LL"}];
const St=({v,s=14})=><span style={{display:"inline-flex",alignItems:"center",gap:1}}>{[1,2,3,4,5].map(i=><span key={i} style={{fontSize:s,color:v>=i?"#F59E0B":v>=i-.5?"#FCD34D":"#D1D5DB"}}>★</span>)}<span style={{fontSize:Math.max(s*.8,11),fontWeight:700,color:C.m,marginLeft:3}}>{v.toFixed(1)}</span></span>;
const Bg=({children,bg="#E0F2FE",fg="#0369A1"})=><span style={{display:"inline-block",padding:"4px 10px",borderRadius:20,fontSize:11,fontWeight:700,background:bg,color:fg,whiteSpace:"nowrap"}}>{children}</span>;
const Lk=({href,ch})=><a href={href} target="_blank" rel="noopener noreferrer" style={{color:C.p,textDecoration:"none",fontWeight:700}}>{ch}</a>;
const gm=a=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(a)}`;
const PB=({p})=>p==="gold"?<Bg bg="#FEF3C7" fg="#92400E">🏅 Gold Pass</Bg>:p==="state"?<Bg bg="#D1FAE5" fg="#065F46">🌲 State Park</Bg>:p==="free"?<Bg bg="#E0F2FE" fg="#0369A1">✨ Free</Bg>:null;
const ld=(k,d)=>{try{return JSON.parse(localStorage.getItem("cpg_"+k))||d}catch{return d}};
const sv=(k,v)=>{try{localStorage.setItem("cpg_"+k,JSON.stringify(v))}catch{}};
const Av=({i,c})=><div style={{width:48,height:48,borderRadius:48,padding:2,background:"linear-gradient(45deg,#f09433,#e6683c,#dc2743,#cc2366,#bc1888)",flexShrink:0}}><div style={{width:44,height:44,borderRadius:44,background:c,display:"flex",alignItems:"center",justifyContent:"center"}}><span style={{fontWeight:900,fontSize:15,color:"#444",fontFamily:"'Lilita One',cursive"}}>{i}</span></div></div>;
const OV={position:"fixed",inset:0,zIndex:2000,background:"rgba(0,0,0,.4)",display:"flex",alignItems:"center",justifyContent:"center",padding:16};
const BX={background:"white",borderRadius:20,padding:"26px 20px",maxWidth:400,width:"calc(100% - 32px)",boxShadow:"0 16px 32px rgba(0,0,0,.15)"};
const IX={width:"100%",padding:"10px 14px",borderRadius:10,border:`2px solid ${C.b}`,fontSize:14,marginBottom:8,boxSizing:"border-box",fontFamily:"inherit",outline:"none",color:C.t};
const CModal=({x})=>{const[ok,so]=useState(false);const[tp,st]=useState("playground");const[nm,sn]=useState("");const[em,se]=useState("");const[mg,sm]=useState("");const[si,ss]=useState(false);const sub=async()=>{ss(true);try{await fetch("https://formspree.io/f/YOUR_FORM_ID",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:tp,name:nm,email:em,message:mg})})}catch{}so(true);ss(false)};if(ok)return<div style={OV} onClick={x}><div onClick={e=>e.stopPropagation()} style={{...BX,textAlign:"center"}}><div style={{fontSize:48}}>✅</div><h3 style={{fontFamily:"'Lilita One',cursive",fontSize:20,color:C.p,margin:"10px 0"}}>Thanks!</h3><button onClick={x} style={{padding:"8px 20px",borderRadius:12,background:C.a,color:"white",border:"none",fontWeight:700,cursor:"pointer",fontFamily:"inherit"}}>Close</button></div></div>;return<div style={OV} onClick={x}><div onClick={e=>e.stopPropagation()} style={{...BX,maxHeight:"85vh",overflowY:"auto"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:10}}><h2 style={{fontFamily:"'Lilita One',cursive",fontSize:18,color:C.p,margin:0}}>📬 Tip</h2><button onClick={x} style={{background:"none",border:"none",fontSize:18,cursor:"pointer"}}>✕</button></div><div style={{display:"flex",gap:5,marginBottom:10,flexWrap:"wrap"}}>{[["playground","🛝"],["tip","💡"],["restaurant","🍽️"],["other","💬"]].map(([v,l])=><button key={v} onClick={()=>st(v)} style={{padding:"5px 10px",borderRadius:16,border:`2px solid ${tp===v?C.a:C.b}`,background:tp===v?C.al:"white",color:tp===v?C.a:C.m,fontWeight:700,fontSize:11,cursor:"pointer",fontFamily:"inherit"}}>{l}</button>)}</div><input value={nm} onChange={e=>sn(e.target.value)} placeholder="Name" style={IX}/><input value={em} onChange={e=>se(e.target.value)} placeholder="Email (opt)" style={IX}/><textarea value={mg} onChange={e=>sm(e.target.value)} placeholder="Tell us..." rows={3} style={{...IX,resize:"vertical"}}/><p style={{fontSize:10,color:C.m,margin:"0 0 8px"}}>Info stays private.</p><button onClick={sub} disabled={!mg.trim()||si} style={{width:"100%",padding:"12px",borderRadius:12,background:mg.trim()?C.a:"#ccc",color:"white",border:"none",fontSize:15,fontWeight:800,cursor:mg.trim()?"pointer":"not-allowed",fontFamily:"inherit"}}>{si?"...":"Submit →"}</button></div></div>};
const AModal=({x,au})=>{const[e,se]=useState("");const[n,sn]=useState("");const[ok,so]=useState(false);return<div style={OV} onClick={x}><div onClick={ev=>ev.stopPropagation()} style={BX}><div style={{fontSize:40,textAlign:"center"}}>🛝</div><h2 style={{fontFamily:"'Lilita One',cursive",fontSize:20,color:C.p,margin:"6px 0",textAlign:"center"}}>Join!</h2><p style={{color:C.m,fontSize:13,textAlign:"center",margin:"0 0 16px"}}>Save favorites & rate playgrounds.</p><input value={n} onChange={ev=>sn(ev.target.value)} placeholder="Name" style={IX}/><input value={e} onChange={ev=>se(ev.target.value)} placeholder="Email" type="email" style={IX}/><label style={{display:"flex",gap:6,alignItems:"flex-start",margin:"2px 0 10px",cursor:"pointer"}}><input type="checkbox" checked={ok} onChange={ev=>so(ev.target.checked)} style={{marginTop:2,width:16,height:16,accentColor:C.p}}/><span style={{fontSize:11,color:C.m,lineHeight:1.3}}>OK to email me updates. Never spam.</span></label><button onClick={()=>{if(e.includes("@")&&ok)au({name:n,email:e})}} disabled={!e.includes("@")||!ok} style={{width:"100%",padding:"13px",borderRadius:12,background:(e.includes("@")&&ok)?C.a:"#ccc",color:"white",border:"none",fontSize:16,fontWeight:800,cursor:(e.includes("@")&&ok)?"pointer":"not-allowed",fontFamily:"inherit"}}>Go! 🎉</button><button onClick={x} style={{width:"100%",marginTop:4,padding:"8px",background:"none",border:"none",color:C.m,fontSize:12,cursor:"pointer",fontFamily:"inherit"}}>Just browsing</button></div></div>};

export default function App(){
const[vw,sV]=useState("playgrounds");const[ar,sA]=useState("All");const[tg,sT]=useState([]);const[so,sS]=useState("overall");const[sr,sSr]=useState("");const[dt,sD]=useState(null);const[fv,sFv]=useState(()=>ld("fv",[]));const[bk,sBk]=useState(()=>ld("bk",[]));const[vi,sVi]=useState(()=>ld("vi",[]));const[sp,sSp]=useState(false);const[us,sUs]=useState(()=>ld("us",null));const[sa,sSa]=useState(false);const[sc,sSc]=useState(false);const[ur,sUr]=useState(()=>ld("ur",{}));const[ed,sEd]=useState(false);
useEffect(()=>sv("fv",fv),[fv]);useEffect(()=>sv("bk",bk),[bk]);useEffect(()=>sv("vi",vi),[vi]);useEffect(()=>sv("us",us),[us]);useEffect(()=>sv("ur",ur),[ur]);
const gd=useCallback(fn=>(...a)=>{if(!us){sSa(true);return}fn(...a)},[us]);
const tF=gd(id=>sFv(p=>p.includes(id)?p.filter(x=>x!==id):[...p,id]));
const tB=gd(id=>sBk(p=>p.includes(id)?p.filter(x=>x!==id):[...p,id]));
const tV=gd(id=>sVi(p=>p.includes(id)?p.filter(x=>x!==id):[...p,id]));
const fl=useMemo(()=>{let r=D;if(ar!=="All")r=r.filter(p=>p.a===ar);if(tg.length)r=r.filter(p=>tg.every(t=>p.t.includes(t)));if(sr){const s=sr.toLowerCase();r=r.filter(p=>p.n.toLowerCase().includes(s)||p.d.toLowerCase().includes(s)||p.a.toLowerCase().includes(s))}return[...r].sort((a,b)=>(b.r[so]||0)-(a.r[so]||0))},[ar,tg,sr,so]);
const bp=bk.length?Math.round((bk.filter(id=>vi.includes(id)).length/bk.length)*100):0;
const Ft=()=><div style={{textAlign:"center",marginTop:36,paddingTop:16,borderTop:`1px solid ${C.b}`}}><button onClick={()=>sSc(true)} style={{background:"none",border:`2px solid ${C.a}`,borderRadius:24,padding:"7px 18px",color:C.a,fontWeight:700,fontSize:12,cursor:"pointer",fontFamily:"inherit"}}>📬 Submit a Tip</button></div>;

/* THE FIX: One single column wrapper for the ENTIRE app.
   Everything — header, nav, content, footer — lives inside
   this fixed-width column. No full-bleed backgrounds. */

return(
<div style={{width:"100%",minHeight:"100vh",background:C.bg,fontFamily:"'Nunito',sans-serif",color:C.t}}>
<style>{`@import url('https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700;800;900&family=Lilita+One&display=swap');*{box-sizing:border-box;-webkit-tap-highlight-color:transparent;margin:0}html{overflow-y:scroll}html,body{overflow-x:hidden;margin:0;padding:0;width:100%;font-family:'Nunito',sans-serif;background:${C.bg}}select,select option{color:${C.t}!important;background:white!important}input::placeholder,textarea::placeholder{color:#999!important;opacity:1!important}@media(max-width:768px){.cr{flex-direction:column!important}.ci{width:100%!important;height:180px!important}.g2{grid-template-columns:1fr!important}}`}</style>
{sa&&<AModal x={()=>sSa(false)} au={u=>{sUs(u);sSa(false)}}/>}{sc&&<CModal x={()=>sSc(false)}/>}

{/* ═══ FIXED-WIDTH COLUMN — 720px max, always centered ═══ */}
<div style={{width:"100%",maxWidth:720,margin:"0 auto",padding:"0 16px"}}>

{/* HEADER */}
<div style={{background:`linear-gradient(135deg,${C.p},#40916C,${C.pd})`,color:"white",padding:"14px 16px",borderRadius:"0 0 16px 16px",marginBottom:0}}>
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}>
<div style={{cursor:"pointer"}} onClick={()=>{sV("playgrounds");sD(null)}}><h1 style={{fontFamily:"'Lilita One',cursive",fontSize:20,margin:0}}>🛝 Charleston Playgrounds</h1><p style={{fontSize:11,opacity:.85,margin:"2px 0 0",fontWeight:600}}>35 playgrounds ✦ rated & reviewed ✦ 2026</p></div>
<div style={{display:"flex",gap:5}}><button onClick={()=>sSc(true)} style={{background:"rgba(255,255,255,.2)",border:"none",borderRadius:8,padding:"6px 10px",color:"white",fontSize:11,fontWeight:700,cursor:"pointer",fontFamily:"inherit"}}>📬</button><button onClick={()=>us?sSp(!sp):sSa(true)} style={{background:"rgba(255,255,255,.2)",border:"none",borderRadius:8,padding:"6px 10px",color:"white",fontSize:11,fontWeight:700,cursor:"pointer",fontFamily:"inherit"}}>{us?`👋 ${us.name||"Me"}`:"Sign In"}</button></div></div></div>

{/* NAV */}
<div style={{background:C.cd,border:`1px solid ${C.b}`,borderTop:"none",borderRadius:"0 0 12px 12px",display:"flex",overflowX:"auto",position:"sticky",top:0,zIndex:100}}>
{[["playgrounds","Playgrounds","🛝"],["activities","Activities","🎪"],["beaches","Beaches","🏖️"],["libraries","Libraries","📚"],["passes","Passes","🎫"],["community","Community","💬"]].map(([k,l,i])=><button key={k} onClick={()=>{sV(k);sD(null)}} style={{flex:"1 0 auto",padding:"10px 6px",border:"none",background:"none",cursor:"pointer",fontFamily:"inherit",fontSize:11,fontWeight:vw===k?800:600,color:vw===k?C.p:C.m,borderBottom:vw===k?`3px solid ${C.a}`:"3px solid transparent",whiteSpace:"nowrap"}}>{i} {l}</button>)}
</div>

{/* PROFILE */}
{sp&&us&&<div style={{background:C.w,border:`1px solid ${C.b}`,borderRadius:12,padding:14,marginTop:10}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:8}}><span style={{fontFamily:"'Lilita One',cursive",fontSize:16,color:C.p}}>🎒 Dashboard</span><div><button onClick={()=>{sUs(null);sSp(false);sv("us",null)}} style={{background:"none",border:"none",color:C.m,fontSize:11,cursor:"pointer",fontFamily:"inherit"}}>Log Out</button> <button onClick={()=>sEd(!ed)} style={{fontSize:11,cursor:"pointer",fontFamily:"inherit",background:"none",border:`1px solid ${C.p}`,borderRadius:6,padding:"2px 8px",color:C.p,fontWeight:700}}>✏️</button> <button onClick={()=>sSp(false)} style={{background:"none",border:"none",fontSize:14,cursor:"pointer"}}>✕</button></div></div><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:6}} className="g2">{[["Fav",fv.length,"❤️","#FEE2E2"],["List",bk.length,"🪣","#DBEAFE"],["Done",vi.length,"✅","#D1FAE5"],["Rate",Object.keys(ur).length,"⭐","#FEF3C7"]].map(([l,v,i,c])=><div key={l} style={{background:c,borderRadius:10,padding:8,textAlign:"center"}}><div style={{fontSize:16}}>{i}</div><div style={{fontSize:16,fontWeight:900}}>{v}</div><div style={{fontSize:9,fontWeight:700,color:C.m}}>{l}</div></div>)}</div>{ed&&<div style={{marginTop:8,padding:10,background:C.cd,borderRadius:10,border:`2px solid ${C.a}`}}><input defaultValue={us.name} id="pn" placeholder="Name" style={IX}/><input defaultValue={us.email} id="pe" placeholder="Email" style={IX}/><button onClick={()=>{sUs({...us,name:document.getElementById("pn").value,email:document.getElementById("pe").value});sEd(false)}} style={{padding:"6px 14px",borderRadius:8,background:C.p,color:"white",border:"none",fontWeight:700,fontSize:12,cursor:"pointer",fontFamily:"inherit"}}>Save</button></div>}</div>}

{/* ═══ TAB CONTENT — all inside the same fixed column ═══ */}
<div style={{marginTop:14,minHeight:"calc(100vh - 200px)"}}>

{vw==="playgrounds"&&!dt&&<div>
<input value={sr} onChange={e=>sSr(e.target.value)} placeholder="🔍  Search 35 playgrounds..." style={{width:"100%",padding:"12px 16px",borderRadius:22,border:`2px solid ${C.b}`,fontSize:15,boxSizing:"border-box",fontFamily:"inherit",background:C.cd,outline:"none",color:C.t}} onFocus={e=>e.target.style.borderColor=C.a} onBlur={e=>e.target.style.borderColor=C.b}/>
<div style={{display:"flex",gap:6,marginTop:10,overflowX:"auto",paddingBottom:4,WebkitOverflowScrolling:"touch"}}>{AR.map(a=><button key={a} onClick={()=>sA(a)} style={{padding:"7px 14px",borderRadius:20,border:"none",cursor:"pointer",background:ar===a?C.a:C.cd,color:ar===a?"white":C.t,fontWeight:700,fontSize:12,fontFamily:"inherit",flexShrink:0}}>{a}</button>)}</div>
<div style={{display:"flex",flexWrap:"wrap",gap:4,marginTop:8}}>{Object.entries(TG).map(([k,l])=><button key={k} onClick={()=>sT(p=>p.includes(k)?p.filter(x=>x!==k):[...p,k])} style={{padding:"4px 9px",borderRadius:14,cursor:"pointer",border:tg.includes(k)?`2px solid ${C.a}`:"2px solid transparent",background:tg.includes(k)?C.al:"#EFEDE8",color:tg.includes(k)?C.a:C.m,fontWeight:600,fontSize:10,fontFamily:"inherit"}}>{l}</button>)}</div>
<div style={{display:"flex",alignItems:"center",gap:6,marginTop:10}}><select value={so} onChange={e=>sS(e.target.value)} style={{padding:"5px 10px",borderRadius:10,border:`1px solid ${C.b}`,fontSize:12,fontFamily:"inherit",background:"white",color:C.t}}>{RC.map(c=><option key={c.k} value={c.k}>{c.i} {c.l}</option>)}</select><span style={{marginLeft:"auto",fontSize:12,fontWeight:700,color:C.m}}>{fl.length}</span></div>
<div style={{display:"flex",flexDirection:"column",gap:10,marginTop:10}}>{fl.map(pg=><div key={pg.id} onClick={()=>sD(pg)} style={{background:C.cd,borderRadius:16,overflow:"hidden",cursor:"pointer",border:`1px solid ${C.b}`}}><div className="cr" style={{display:"flex"}}><div className="ci" style={{width:110,minHeight:100,flexShrink:0}}><Ph e={pg.e} h={pg.h} ht={200}/></div><div style={{padding:"10px 12px",flex:1,minWidth:0}}><h3 style={{margin:0,fontSize:14,fontWeight:800,color:C.t}}>{pg.n}</h3><a href={gm(pg.ad)} target="_blank" rel="noopener noreferrer" onClick={e=>e.stopPropagation()} style={{fontSize:11,color:C.p,textDecoration:"none",fontWeight:600}}>📍 {pg.a}</a>{pg.r.overall>0?<div style={{margin:"3px 0"}}><St v={pg.r.overall} s={12}/></div>:<div style={{margin:"3px 0",fontSize:11,color:C.a,fontWeight:700}}>🆕 Rate!</div>}<p style={{margin:0,fontSize:12,color:"#666",lineHeight:1.35,display:"-webkit-box",WebkitLineClamp:2,WebkitBoxOrient:"vertical",overflow:"hidden"}}>{pg.d}</p><div style={{display:"flex",flexWrap:"wrap",gap:3,marginTop:4}}>{pg.p&&<PB p={pg.p}/>}{pg.t.slice(0,3).map(t=><Bg key={t}>{TG[t]}</Bg>)}</div></div></div></div>)}</div><Ft/></div>}

{vw==="playgrounds"&&dt&&(()=>{const p=dt;return<div><button onClick={()=>sD(null)} style={{background:"none",border:"none",cursor:"pointer",fontFamily:"inherit",fontSize:14,fontWeight:700,color:C.p,padding:0,marginBottom:10}}>← Back</button><div style={{background:C.cd,borderRadius:16,overflow:"hidden",border:`1px solid ${C.b}`}}><Ph e={p.e} h={p.h} ht={200}/><div style={{padding:18}}><h2 style={{fontFamily:"'Lilita One',cursive",fontSize:22,color:C.p,margin:"0 0 4px"}}>{p.n}</h2><a href={gm(p.ad)} target="_blank" rel="noopener noreferrer" style={{color:C.p,textDecoration:"none",fontWeight:600,fontSize:13}}>📍 {p.ad}</a><div style={{display:"flex",flexWrap:"wrap",gap:6,margin:"12px 0"}}><button onClick={()=>tF(p.id)} style={{padding:"8px 12px",borderRadius:10,border:`2px solid ${fv.includes(p.id)?C.r:C.b}`,background:fv.includes(p.id)?"#FEE2E2":C.cd,cursor:"pointer",fontFamily:"inherit",fontWeight:700,fontSize:13,color:C.t}}>{fv.includes(p.id)?"❤️ Fav'd":"🤍 Fav"}</button><button onClick={()=>tB(p.id)} style={{padding:"8px 12px",borderRadius:10,border:`2px solid ${bk.includes(p.id)?C.od:C.b}`,background:bk.includes(p.id)?C.o:C.cd,cursor:"pointer",fontFamily:"inherit",fontWeight:700,fontSize:13,color:C.t}}>{bk.includes(p.id)?"🪣 Listed":"🪣 Add"}</button><button onClick={()=>tV(p.id)} style={{padding:"8px 12px",borderRadius:10,border:`2px solid ${vi.includes(p.id)?C.g:C.b}`,background:vi.includes(p.id)?"#D1FAE5":C.cd,cursor:"pointer",fontFamily:"inherit",fontWeight:700,fontSize:13,color:C.t}}>{vi.includes(p.id)?"✅ Done":"☐ Visit"}</button></div><p style={{fontSize:14,lineHeight:1.6,color:"#444",margin:"0 0 12px"}}>{p.d}</p>{p.p&&<div style={{marginBottom:10}}><PB p={p.p}/></div>}<div style={{display:"flex",flexWrap:"wrap",gap:4,marginBottom:16}}>{p.t.map(t=><Bg key={t}>{TG[t]}</Bg>)}</div>
{p.r.overall>0&&<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(155px,1fr))",gap:5,marginBottom:14}} className="g2">{RC.map(c=><div key={c.k} style={{background:"#F5F3EE",borderRadius:10,padding:"7px 10px",display:"flex",justifyContent:"space-between",alignItems:"center"}}><span style={{fontSize:11,fontWeight:700}}>{c.i} {c.l}</span><St v={p.r[c.k]||0} s={11}/></div>)}</div>}
<div style={{background:C.w,borderRadius:12,padding:12,marginBottom:14}}><h4 style={{margin:"0 0 6px",fontWeight:800,fontSize:13}}>⭐ Rate</h4><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(155px,1fr))",gap:4}} className="g2">{RC.map(c=><div key={c.k} style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><span style={{fontSize:11,fontWeight:600}}>{c.i} {c.l}</span><div>{[1,2,3,4,5].map(x=><button key={x} onClick={gd(()=>sUr(prev=>({...prev,[`${p.id}-${c.k}`]:x})))} style={{background:"none",border:"none",fontSize:18,cursor:"pointer",padding:"0 1px",color:(ur[`${p.id}-${c.k}`]||0)>=x?"#F59E0B":"#D1D5DB"}}>★</button>)}</div></div>)}</div></div>
{p.f?.length>0&&<div style={{marginBottom:14}}><h4 style={{fontFamily:"'Lilita One',cursive",fontSize:15,color:C.p,margin:"0 0 6px"}}>🍽️ Eats</h4>{p.f.map((r,i)=><a key={i} href={gm(r.a)} target="_blank" rel="noopener noreferrer" style={{display:"block",background:"#F5F3EE",borderRadius:10,padding:"10px 12px",textDecoration:"none",color:C.t,border:`1px solid ${C.b}`,marginBottom:4}}><b>{r.n}</b> <Bg bg={C.pl} fg={C.p}>{r.t}</Bg><br/><span style={{fontSize:12,color:C.m}}>{r.d} · 📍 {r.a}</span></a>)}</div>}
<a href={gm(p.ad)} target="_blank" rel="noopener noreferrer" style={{display:"inline-block",padding:"12px 20px",background:C.a,color:"white",borderRadius:14,textDecoration:"none",fontWeight:800,fontSize:14,fontFamily:"inherit"}}>📍 Directions</a></div></div><Ft/></div>})()}

{vw==="activities"&&<div><h2 style={{fontFamily:"'Lilita One',cursive",fontSize:20,color:C.p,margin:"0 0 12px"}}>🎪 Things to Do</h2>{AC.map((a,i)=><div key={i} style={{background:C.cd,borderRadius:14,padding:14,border:`1px solid ${C.b}`,marginBottom:8}}><div style={{display:"flex",gap:10,alignItems:"flex-start"}}><div style={{fontSize:24,width:38,height:38,display:"flex",alignItems:"center",justifyContent:"center",background:"#F5F3EE",borderRadius:10,flexShrink:0}}>{a.ic}</div><div style={{flex:1}}><Lk href={a.ur} ch={<span style={{fontSize:14,fontWeight:800,color:C.t}}>{a.n} ↗</span>}/><br/><a href={gm(a.ad)} target="_blank" rel="noopener noreferrer" style={{fontSize:11,color:C.p,textDecoration:"none",fontWeight:600}}>📍 {a.ad}</a><p style={{margin:"3px 0",fontSize:13,color:"#555",lineHeight:1.4}}>{a.ds}</p><div style={{fontSize:11,color:C.p,fontWeight:700}}>🕐 {a.hr} · 💰 {a.co}</div></div></div></div>)}<Ft/></div>}

{vw==="beaches"&&<div><h2 style={{fontFamily:"'Lilita One',cursive",fontSize:20,color:C.p,margin:"0 0 10px"}}>🏖️ Beaches</h2>{BH.map((b,i)=><div key={i} style={{background:C.cd,borderRadius:16,padding:18,border:`1px solid ${C.b}`,marginBottom:10}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",flexWrap:"wrap",gap:6,marginBottom:4}}><div><h3 style={{margin:0,fontSize:16,fontWeight:800,color:C.t}}>{b.n}</h3><a href={gm(b.ad)} target="_blank" rel="noopener noreferrer" style={{fontSize:11,color:C.p,textDecoration:"none",fontWeight:600}}>📍 {b.ad}</a></div><PB p={b.ps}/></div><p style={{fontSize:13,lineHeight:1.5,color:"#444",margin:"0 0 8px"}}>{b.ds}</p><div style={{background:"#F5F3EE",borderRadius:12,padding:"10px 12px"}}>{b.tp.map((t,j)=><div key={j} style={{fontSize:12,lineHeight:1.6,color:"#444"}}>{t}</div>)}</div></div>)}<Ft/></div>}

{vw==="libraries"&&<div><h2 style={{fontFamily:"'Lilita One',cursive",fontSize:20,color:C.p,margin:"0 0 6px"}}>📚 Storytimes</h2><div style={{background:C.pl,borderRadius:10,padding:"8px 12px",margin:"6px 0 10px",fontSize:12,fontWeight:600}}>💡 Ask about Storytime Kits & Explore with CCPL!</div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(260px,1fr))",gap:8}} className="g2">{LB.map((l,i)=><div key={i} style={{background:C.cd,borderRadius:12,padding:14,border:`1px solid ${C.b}`}}><h3 style={{margin:"0 0 2px",fontSize:14,fontWeight:800}}>📚 {l.n}</h3><a href={gm(l.ad)} target="_blank" rel="noopener noreferrer" style={{fontSize:11,color:C.p,textDecoration:"none",fontWeight:600}}>📍 {l.ad}</a><p style={{margin:"3px 0",fontSize:12,color:"#555"}}>{l.nt}</p></div>)}</div><Ft/></div>}

{vw==="passes"&&<div><h2 style={{fontFamily:"'Lilita One',cursive",fontSize:20,color:C.p,margin:"0 0 10px"}}>🎫 Passes 2026</h2>
<div style={{background:"linear-gradient(135deg,#FEF3C7,#FDE68A)",borderRadius:16,padding:18,border:"2px solid #F59E0B",marginBottom:10}}><h3 style={{margin:0,fontSize:17,fontWeight:900,color:"#78350F"}}>🏅 Gold Pass — $99 ($84 res)</h3><p style={{fontSize:11,lineHeight:1.7,color:"#78350F",margin:"4px 0"}}><b>Parks:</b> James Is · Palmetto Is · Wannamaker · Caw Caw · Johns Is · McLeod · Laurel Hill · Lighthouse Inlet · Meggett · Stono River · West County Aquatic<br/><b>Beaches:</b> Folly · IOP · Kiawah · <b>Events:</b> Harvest · Lights · Latin · Cajun · Reggae</p><Lk href="https://www.ccprc.com/16/Park-Passes" ch={<span style={{color:"#78350F",fontSize:12}}>Buy →</span>}/></div>
<div style={{background:"linear-gradient(135deg,#D1FAE5,#A7F3D0)",borderRadius:16,padding:18,border:"2px solid #059669",marginBottom:10}}><h3 style={{margin:0,fontSize:17,fontWeight:900,color:"#064E3B"}}>🌲 State Park — $99</h3><p style={{fontSize:11,lineHeight:1.7,color:"#064E3B",margin:"4px 0"}}><b>Near CHS:</b> Charles Towne 15m · Dorchester 20m · Givhans 45m · Edisto 1h · Colleton 1h<br/><b>Beaches:</b> Edisto 1h · Hunting Is 2h · Huntington 2h · Myrtle 2.5h</p><Lk href="https://southcarolinaparks.com" ch={<span style={{color:"#064E3B",fontSize:12}}>Buy →</span>}/></div>
<div style={{background:"linear-gradient(135deg,#E0F2FE,#BAE6FD)",borderRadius:16,padding:18,border:"2px solid #0284C7",marginBottom:10}}><h3 style={{margin:0,fontSize:17,fontWeight:900,color:"#0C4A6E"}}>📚 CCPL — Free!</h3><p style={{fontSize:12,color:"#0C4A6E",margin:"4px 0"}}>Borrow: Aquarium, Museum, Gibbes, Parks, Gold Pass!</p><Lk href="https://www.ccpl.org" ch={<span style={{color:"#0C4A6E",fontSize:12}}>CCPL →</span>}/></div>
<div style={{background:C.cd,borderRadius:16,padding:18,border:`1px solid ${C.b}`,marginBottom:10}}><h3 style={{margin:0,fontSize:17,fontWeight:900}}>🐠 SC Aquarium</h3><p style={{fontSize:12,color:"#555",margin:"4px 0",lineHeight:1.6}}><b>Day:</b> ~$30-45 · <b>Adult:</b> $99/yr · <b>Family:</b> $249 · <b>Family+:</b> $319 · <b>Angelfish:</b> $40 · Military 15% · Teachers free · Gold Pass $15 off · Library free 1wk</p><Lk href="https://scaquarium.org/membership/" ch={<span style={{fontSize:12}}>Details →</span>}/></div>
<div style={{background:C.cd,borderRadius:16,padding:18,border:`1px solid ${C.b}`,marginBottom:10}}><h3 style={{margin:0,fontSize:17,fontWeight:900}}>🎨 Children's Museum</h3><p style={{fontSize:12,color:"#555",margin:"4px 0",lineHeight:1.6}}><b>Day:</b> $15/$13/$3 · <b>Hours:</b> M-Sa 10-5, Su 12-5 · Members 9am · SuperStars Sun FREE · Quarter Day 25¢!</p><Lk href="https://explorecml.org/visit/" ch={<span style={{fontSize:12}}>Visit →</span>}/></div>
<div style={{background:C.cd,borderRadius:16,padding:18,border:`1px solid ${C.b}`}}><h3 style={{margin:0,fontSize:17,fontWeight:900}}>🌊 Splash Pass — ~$100+</h3><p style={{fontSize:12,color:"#555",margin:"4px 0"}}>Seasonal. Whirlin' Waters, Splash Zone, Splash Island.</p><Lk href="https://www.ccprc.com/16/Park-Passes" ch={<span style={{fontSize:12}}>Buy →</span>}/></div>
<Ft/></div>}

{vw==="community"&&<div><h2 style={{fontFamily:"'Lilita One',cursive",fontSize:20,color:C.p,margin:"0 0 10px"}}>💬 Community</h2>{CM.map(c=><a key={c.h} href={c.u} target="_blank" rel="noopener noreferrer" style={{display:"flex",gap:12,alignItems:"center",background:C.cd,borderRadius:14,padding:"12px 14px",border:`1px solid ${C.b}`,textDecoration:"none",color:C.t,marginBottom:8}}><Av i={c.i} c={c.c}/><div><div style={{fontWeight:800,fontSize:15,color:C.t}}>{c.nm}</div><div style={{fontSize:12,color:C.a,fontWeight:700}}>{c.h}</div><div style={{fontSize:12,color:C.m,marginTop:1}}>{c.ds}</div></div></a>)}
<h3 style={{fontFamily:"'Lilita One',cursive",fontSize:16,color:C.p,margin:"14px 0 8px"}}>Resources</h3><div style={{display:"grid",gridTemplateColumns:"repeat(2,1fr)",gap:8}} className="g2">{[["Kidding Around CHS","Events","https://kiddingaroundcharleston.com","🎉"],["Charleston Moms","Guides","https://charlestonmoms.com","👩‍👧‍👦"],["Lowcountry Parent","News","https://www.postandcourier.com/lowcountryparent/","📰"],["CCPL Events","Storytimes","https://ccplsc.libcal.com/calendar","📅"]].map(([n,d,u,i])=><a key={n} href={u} target="_blank" rel="noopener noreferrer" style={{background:C.cd,borderRadius:12,padding:12,border:`1px solid ${C.b}`,textDecoration:"none",color:C.t}}><div style={{fontSize:18,marginBottom:2}}>{i}</div><div style={{fontWeight:800,fontSize:12}}>{n}</div><div style={{fontSize:11,color:C.m}}>{d}</div></a>)}</div><Ft/></div>}

</div>{/* end tab content */}

{/* FOOTER */}
<div style={{background:C.pd,color:"rgba(255,255,255,.7)",textAlign:"center",padding:"16px",fontSize:11,lineHeight:1.7,borderRadius:"12px 12px 0 0",marginTop:20}}><div style={{fontFamily:"'Lilita One',cursive",fontSize:14,color:"white"}}>🛝 charlestonplaygrounds.com</div><p style={{margin:0}}>35 playgrounds · March 2026 · Made with ❤️</p></div>

</div>{/* end fixed-width column */}
</div>);}
