import{useState,useEffect,useMemo,useCallback}from"react";

/* charlestonplaygrounds.com — March 2026 — 35 playgrounds
   ARCHITECTURE: One fixed 720px column wraps EVERYTHING.
   One reusable Card component used on EVERY tab.
   Identical spacing, padding, and margins everywhere. */

const $={bg:"#F0EDE4",cd:"#FFFDF8",p:"#2D6A4F",pd:"#1B4332",pl:"#D8F3DC",a:"#F4845F",al:"#FDDDD2",t:"#1B1B1E",m:"#7C7C7C",b:"#DDD8CE",o:"#CAF0F8",od:"#0077B6",w:"#FFF8F0"};
const TG={fenced:"🔒 Fenced",shade:"🌳 Shaded",splashpad:"💦 Splash Pad",restrooms:"🚻 Restrooms",toddler:"👶 Toddler",parking:"🅿️ Parking",dogs:"🐕 Dogs OK",food:"🍔 Food",stroller:"🛤️ Strollers",inclusive:"♿ Inclusive",swings:"🎪 Swings",picnic:"🧺 Picnic"};
const AR=["All","Downtown","West Ashley","Mt. Pleasant","North Charleston","James Island","Johns Island","Daniel Island","Sullivan's Island","Folly Beach","Isle of Palms","Kiawah Island"];
const RC=[{k:"overall",l:"Overall",i:"⭐"},{k:"shade",l:"Shade",i:"🌳"},{k:"equipment",l:"Equipment",i:"🎠"},{k:"cleanliness",l:"Clean",i:"✨"},{k:"bugs",l:"Low(er) Bugs",i:"🦟"},{k:"safety",l:"Safety",i:"🛡️"},{k:"toddlerFriendly",l:"Tot-Friendly",i:"👶"},{k:"nearbyFood",l:"Food Nearby",i:"🍕"}];
const PG=[
{id:1,n:"Bridgepoint Ecological Park",a:"West Ashley",ad:"West Ashley, SC 29407",e:"🌿",h:110,t:["fenced","stroller"],r:{overall:0,shade:0,equipment:0,cleanliness:0,bugs:0,safety:0,toddlerFriendly:0,nearbyFood:0},d:"Brand new March 2026! Resilient design, audio tours via QR codes.",p:null,f:[]},
{id:2,n:"Randolph Park",a:"West Ashley",ad:"Randolph Park, West Ashley, SC",e:"🌳",h:80,t:["shade","toddler","picnic"],r:{overall:4.0,shade:5,equipment:3.5,cleanliness:4,bugs:3,safety:4,toddlerFriendly:4.5,nearbyFood:3},d:"Heavy oak shade, fireplace shelter. Toddler hub.",p:null,f:[]},
{id:3,n:"West Ashley Park",a:"West Ashley",ad:"3601 Mary Ader Dr, Charleston, SC 29414",e:"🎣",h:90,t:["shade","restrooms","toddler","parking","dogs","stroller","swings","picnic"],r:{overall:4.5,shade:4,equipment:4.5,cleanliness:4,bugs:3,safety:4,toddlerFriendly:4.5,nearbyFood:3},d:"260 acres — TWO playgrounds, fishing, disc golf, trails.",p:null,f:[{n:"Swig & Swine",t:"BBQ",d:"Kid-friendly.",a:"1217 Savannah Hwy"},{n:"Boxcar Betty's",t:"Sandwiches",d:"Fried chicken.",a:"1922 Savannah Hwy"}]},
{id:4,n:"Mulberry Park",a:"West Ashley",ad:"Mulberry Park, West Ashley, SC",e:"🍊",h:50,t:["shade","stroller"],r:{overall:3.8,shade:4,equipment:3.5,cleanliness:4,bugs:3,safety:4,toddlerFriendly:3.5,nearbyFood:2},d:"Food Forest — citrus and herbs!",p:null,f:[]},
{id:5,n:"Mary Utsey (Orange Grove)",a:"West Ashley",ad:"1350 Orange Grove Rd, Charleston",e:"🎡",h:45,t:["inclusive","toddler","parking","swings"],r:{overall:4.1,shade:3,equipment:4,cleanliness:4,bugs:3,safety:4,toddlerFriendly:4.5,nearbyFood:3},d:"Sensory-friendly — roller slides, expression swings.",p:null,f:[]},
{id:6,n:"Bees Landing Rec",a:"West Ashley",ad:"Bees Landing, West Ashley, SC",e:"🐝",h:55,t:["restrooms","toddler","parking","dogs"],r:{overall:4.2,shade:3.5,equipment:4.5,cleanliness:4.5,bugs:3,safety:4.5,toddlerFriendly:4,nearbyFood:3},d:"Modern equipment, rubberized floor, dog park.",p:null,f:[]},
{id:7,n:"Lenevar Playground",a:"West Ashley",ad:"Lenevar Park, West Ashley, SC",e:"🎾",h:65,t:["toddler","swings"],r:{overall:3.7,shade:3,equipment:3.5,cleanliness:3.5,bugs:3,safety:3.5,toddlerFriendly:3.5,nearbyFood:2.5},d:"Renovated — tennis, exercise stations. No bathrooms.",p:null,f:[]},
{id:8,n:"Parkshore Park",a:"West Ashley",ad:"Parkshore Park, West Ashley, SC",e:"🌲",h:130,t:["shade","stroller","parking"],r:{overall:3.9,shade:5,equipment:3,cleanliness:4,bugs:2.5,safety:4,toddlerFriendly:3,nearbyFood:2},d:"10 wooded acres, 0.5-mile trail.",p:null,f:[]},
{id:9,n:"Ackerman Park",a:"West Ashley",ad:"55 Sycamore Ave, Charleston, SC",e:"🛹",h:60,t:["toddler","dogs","parking","swings","fenced"],r:{overall:4.2,shade:2.5,equipment:4,cleanliness:4,bugs:3,safety:4,toddlerFriendly:4,nearbyFood:3.5},d:"Fenced, next to skate park. Dog park.",p:null,f:[{n:"Edmund's Oast",t:"Brewery",d:"Lawn for kids.",a:"1505 King St Ext"}]},
{id:10,n:"Magnolia Children's Garden",a:"West Ashley",ad:"3550 Ashley River Rd, Charleston",e:"🧚",h:300,t:["shade","restrooms","stroller","parking"],r:{overall:4.7,shade:5,equipment:4,cleanliness:5,bugs:2.5,safety:4.5,toddlerFriendly:5,nearbyFood:2},d:"Fairy garden — gnomes, storybook walk.",p:null,f:[]},
{id:11,n:"James Island County Park",a:"James Island",ad:"871 Riverland Dr, Charleston, SC",e:"🎄",h:30,t:["shade","restrooms","splashpad","toddler","parking","dogs","stroller","swings","picnic"],r:{overall:4.8,shade:4.5,equipment:4.5,cleanliness:5,bugs:3,safety:5,toddlerFriendly:5,nearbyFood:2.5},d:"Massive — splash pad, climbing wall, Holiday Lights.",p:"gold",f:[{n:"Kickin' Chicken",t:"Chicken",d:"Kids love tenders.",a:"1626 Camp Rd"}]},
{id:12,n:"Plymouth Park",a:"James Island",ad:"1309 Ft Johnson Rd, Charleston",e:"🌊",h:190,t:["shade","toddler","swings","picnic"],r:{overall:4.2,shade:5,equipment:3.5,cleanliness:3.5,bugs:3,safety:4,toddlerFriendly:4,nearbyFood:3},d:"Oak shade, Wappoo Creek. Fire station!",p:null,f:[]},
{id:13,n:"JI Recreation Complex",a:"James Island",ad:"JI Rec, Charleston, SC",e:"⚽",h:75,t:["restrooms","toddler","parking","swings"],r:{overall:4.0,shade:3,equipment:4,cleanliness:4,bugs:3,safety:4,toddlerFriendly:4,nearbyFood:3},d:"Playground, sports fields, pool.",p:null,f:[]},
{id:14,n:"Wave Watch Playground",a:"Folly Beach",ad:"500 W Cooper Ave, Folly Beach",e:"🌊",h:195,t:["fenced","shade","restrooms","toddler","parking","swings"],r:{overall:4.3,shade:4,equipment:4,cleanliness:4,bugs:3,safety:4.5,toddlerFriendly:4.5,nearbyFood:4},d:"Fully fenced! Oceanfront murals, gazebo, Little Library. 7:30am–8:30pm.",p:null,f:[{n:"Lost Dog Café",t:"Café",d:"Wraps, salads.",a:"106 W Huron Ave"}]},
{id:15,n:"Pirates Cove",a:"Folly Beach",ad:"Pirates Cove, Folly Beach, SC",e:"🏴‍☠️",h:180,t:["shade","restrooms","toddler","parking","swings","picnic"],r:{overall:4.4,shade:4,equipment:4,cleanliness:4,bugs:3,safety:4,toddlerFriendly:4,nearbyFood:4.5},d:"Pirate ship, lighthouse slide, skate park.",p:null,f:[]},
{id:16,n:"Johns Island County Park",a:"Johns Island",ad:"Johns Island County Park, SC",e:"🏹",h:100,t:["shade","restrooms","parking","stroller"],r:{overall:4.1,shade:4,equipment:3.5,cleanliness:4,bugs:2.5,safety:4,toddlerFriendly:3,nearbyFood:2},d:"Nature trails, archery, climbing.",p:"gold",f:[]},
{id:17,n:"Johns Island Park",a:"Johns Island",ad:"Johns Island Park, SC",e:"🏃",h:85,t:["toddler","parking","swings","restrooms"],r:{overall:3.9,shade:3,equipment:3.5,cleanliness:4,bugs:3,safety:4,toddlerFriendly:4,nearbyFood:2.5},d:"'Tot Lot' and sports fields.",p:null,f:[]},
{id:18,n:"Stono River County Park",a:"Johns Island",ad:"Stono River County Park, SC",e:"🦢",h:140,t:["shade","parking","stroller"],r:{overall:3.8,shade:4.5,equipment:2.5,cleanliness:4,bugs:2.5,safety:4,toddlerFriendly:2.5,nearbyFood:2},d:"Marsh boardwalks, scenic trails.",p:"gold",f:[]},
{id:19,n:"Hampton Park",a:"Downtown",ad:"30 Mary Murray Dr, Charleston, SC",e:"🦆",h:120,t:["shade","stroller","toddler","dogs","picnic"],r:{overall:4.6,shade:5,equipment:4,cleanliness:4.5,bugs:3,safety:4.5,toddlerFriendly:5,nearbyFood:3.5},d:"Historic — duck pond, trail loops.",p:null,f:[{n:"Basic Kitchen",t:"Healthy",d:"Plant-based.",a:"82 Wentworth St"},{n:"Rodney Scott's",t:"BBQ",d:"Whole-hog.",a:"1011 King St"}]},
{id:20,n:"Gadsdenboro Park",a:"Downtown",ad:"30 Concord St, Charleston, SC",e:"⚓",h:210,t:["shade","stroller","toddler","food","swings"],r:{overall:4.3,shade:3.5,equipment:4,cleanliness:4,bugs:3.5,safety:4,toddlerFriendly:4,nearbyFood:5},d:"Net-climbing near Aquarium. Ravenel views.",p:null,f:[{n:"Harken Café",t:"Bakery",d:"Pastries.",a:"62 Queen St"}]},
{id:21,n:"Hazel Parker",a:"Downtown",ad:"70 East Bay St, Charleston, SC",e:"🎾",h:170,t:["shade","restrooms","toddler","dogs","swings","stroller"],r:{overall:4.5,shade:4,equipment:4,cleanliness:4,bugs:3,safety:4,toddlerFriendly:4.5,nearbyFood:5},d:"Waterfront, oak shade, tennis, Battery.",p:null,f:[{n:"Fleet Landing",t:"Seafood",d:"Waterfront.",a:"186 Concord St"}]},
{id:22,n:"Moultrie Playground",a:"Downtown",ad:"Moultrie Playground, Charleston",e:"🧗",h:260,t:["toddler","swings","inclusive"],r:{overall:4.2,shade:3,equipment:4.5,cleanliness:4,bugs:3,safety:4,toddlerFriendly:4,nearbyFood:4},d:"Net structures, rubber surface, pickleball.",p:null,f:[]},
{id:23,n:"Brittlebank Park",a:"Downtown",ad:"Brittlebank Park, Charleston",e:"♿",h:200,t:["inclusive","stroller","restrooms","parking"],r:{overall:4.1,shade:3,equipment:3.5,cleanliness:4,bugs:3,safety:4,toddlerFriendly:3.5,nearbyFood:3.5},d:"Ashley River waterfront, inclusive ramps.",p:null,f:[]},
{id:24,n:"Park Circle",a:"North Charleston",ad:"4800 Park Circle, N. Charleston, SC",e:"🏰",h:150,t:["fenced","shade","inclusive","restrooms","toddler","parking","swings","picnic"],r:{overall:4.9,shade:5,equipment:5,cleanliness:4.5,bugs:3.5,safety:5,toddlerFriendly:5,nearbyFood:4.5},d:"World's Largest Inclusive — 55K sq ft! Ninja, zip lines.",p:null,f:[{n:"EVO Bakery",t:"Pizza",d:"Pizzas, patio.",a:"1075 E Montague"},{n:"Jackrabbit Filly",t:"Farm-table",d:"Veggie-forward.",a:"4628 Spruill Ave"}]},
{id:25,n:"Wannamaker County Park",a:"North Charleston",ad:"8888 University Blvd, N. Charleston",e:"🛹",h:250,t:["shade","restrooms","splashpad","toddler","parking","stroller","swings","picnic"],r:{overall:4.6,shade:5,equipment:4.5,cleanliness:4.5,bugs:3,safety:4.5,toddlerFriendly:4.5,nearbyFood:2},d:"Tot Lot + Fun Lot, splash pad, stroller trails.",p:"gold",f:[]},
{id:26,n:"Palmetto Islands",a:"Mt. Pleasant",ad:"444 Needlerush Pkwy, Mt. Pleasant",e:"🗼",h:140,t:["shade","restrooms","toddler","parking","picnic","swings"],r:{overall:4.7,shade:5,equipment:5,cleanliness:4.5,bugs:2.5,safety:4.5,toddlerFriendly:4.5,nearbyFood:2},d:"'Big Toy' — 50-ft tower with slides.",p:"gold",f:[{n:"Lillie Fuel",t:"Healthy",d:"Order ahead.",a:"426 W Coleman Blvd"}]},
{id:27,n:"Mt. Pleasant Waterfront",a:"Mt. Pleasant",ad:"99 Harry M Hallman Jr Blvd, Mt. Pleasant",e:"🌉",h:200,t:["shade","splashpad","restrooms","toddler","parking","food","stroller","swings","picnic"],r:{overall:4.8,shade:4,equipment:4.5,cleanliness:4.5,bugs:3,safety:4.5,toddlerFriendly:5,nearbyFood:4},d:"Nautical under Ravenel Bridge. Dolphins!",p:null,f:[{n:"Page's Okra",t:"Lowcountry",d:"Great portions.",a:"302 Coleman Blvd"},{n:"Coastal Crust",t:"Pizza",d:"Truck playground!",a:"219 Simmons St"}]},
{id:28,n:"Alhambra Playground",a:"Mt. Pleasant",ad:"Alhambra Hall, Mt. Pleasant",e:"🌳",h:115,t:["shade","toddler","inclusive"],r:{overall:4.1,shade:5,equipment:3.5,cleanliness:4,bugs:3,safety:4,toddlerFriendly:4,nearbyFood:3},d:"Massive oaks, harbor views, sensory-friendly.",p:null,f:[]},
{id:29,n:"Noah's Ark (LifePark)",a:"Mt. Pleasant",ad:"LifePark, Mt. Pleasant",e:"🚢",h:35,t:["fenced","toddler","swings","picnic"],r:{overall:4.3,shade:3.5,equipment:4,cleanliness:4,bugs:3,safety:4.5,toddlerFriendly:4.5,nearbyFood:3},d:"Giant wooden ark, fenced, huge lawn.",p:null,f:[]},
{id:30,n:"IOP County Park",a:"Isle of Palms",ad:"14th Ave, Isle of Palms",e:"🏖️",h:185,t:["restrooms","toddler","parking","swings"],r:{overall:4.3,shade:3,equipment:4,cleanliness:4,bugs:3,safety:4,toddlerFriendly:4,nearbyFood:3.5},d:"Oceanfront, sand play. Right at beach!",p:"gold",f:[]},
{id:31,n:"IOP Recreation",a:"Isle of Palms",ad:"IOP Rec, Isle of Palms",e:"🎪",h:175,t:["toddler","swings","restrooms"],r:{overall:4.2,shade:3,equipment:4.5,cleanliness:4.5,bugs:3,safety:4.5,toddlerFriendly:4,nearbyFood:3},d:"Modern structures, rubber floor, near beach.",p:null,f:[]},
{id:32,n:"Governor's Park",a:"Daniel Island",ad:"Governor's Park, Daniel Island",e:"🏃",h:220,t:["shade","restrooms","parking","stroller","swings"],r:{overall:4.4,shade:4,equipment:4.5,cleanliness:4.5,bugs:3,safety:4.5,toddlerFriendly:4,nearbyFood:3.5},d:"Zip line! Waterfront trails.",p:null,f:[{n:"King's Tide",t:"Waterfront",d:"For families.",a:"1959 Daniel Island Dr"}]},
{id:33,n:"Pirate Cove (Smythe)",a:"Daniel Island",ad:"Smythe Park, Daniel Island",e:"🏴‍☠️",h:160,t:["shade","toddler","swings","picnic"],r:{overall:4.3,shade:4,equipment:4,cleanliness:4.5,bugs:3,safety:4.5,toddlerFriendly:4.5,nearbyFood:3},d:"Pirate ship over the pond.",p:null,f:[]},
{id:34,n:"Beachwalker Park",a:"Kiawah Island",ad:"8 Beachwalker Dr, Kiawah",e:"🐚",h:165,t:["parking","stroller"],r:{overall:3.8,shade:2.5,equipment:3,cleanliness:4,bugs:3,safety:4,toddlerFriendly:3,nearbyFood:1.5},d:"Seasonal beach, boardwalk play.",p:"gold",f:[]},
{id:35,n:"Sullivan's Island Park",a:"Sullivan's Island",ad:"2056 Middle St, Sullivan's Island",e:"🐚",h:155,t:["shade","toddler","food","swings"],r:{overall:4.3,shade:4,equipment:4,cleanliness:4.5,bugs:3,safety:4.5,toddlerFriendly:4,nearbyFood:4.5},d:"Oak canopy. Beach, restaurants, Ft Moultrie.",p:null,f:[{n:"Obstinate Daughter",t:"Italian",d:"Pizza + Beardcats!",a:"2063 Middle St"},{n:"Home Team BBQ",t:"BBQ",d:"Corn hole, $2.75 kids.",a:"2209 Middle St"}]},
];
const AC=[{n:"SC Aquarium",ad:"100 Aquarium Wharf",ic:"🐠",ur:"https://scaquarium.org",hr:"Daily 9–5",co:"~$30-45",ds:"5,000+ animals, touch tanks, sea turtles."},{n:"Children's Museum",ad:"25 Ann St",ic:"🎨",ur:"https://explorecml.org",hr:"M-Sa 10–5, Su 12–5",co:"$15/$13/$3",ds:"Pirate ship, art room. 2–3 hrs."},{n:"Charles Towne Landing",ad:"1500 Old Towne Rd",ic:"🦬",ur:"https://southcarolinaparks.com/charles-towne-landing",hr:"Daily 9–5",co:"$10/$6/$0",ds:"Zoo, ship, 80 acres."},{n:"Pack Athletics WA",ad:"1012 St Andrews Blvd",ic:"🤸",ur:"https://www.allaboutthepack.com",hr:"Varies",co:"Varies",ds:"Cheer, tumbling, ninja, tot gym."},{n:"Pack Athletics MP",ad:"1172 US Hwy 41",ic:"🤸",ur:"https://www.allaboutthepack.com",hr:"Varies",co:"Varies",ds:"Tumbling, cheer, open gym."},{n:"Whirlin' Waters",ad:"8888 University Blvd",ic:"🌊",ur:"https://www.ccprc.com",hr:"May–Sep",co:"Splash Pass",ds:"Slides, lazy river."},{n:"Splash Zone",ad:"871 Riverland Dr",ic:"🦜",ur:"https://www.ccprc.com",hr:"May–Sep",co:"Splash Pass",ds:"Rainforest-themed."},{n:"SK8 Charleston",ad:"8888 University Blvd",ic:"🛹",ur:"https://www.ccprc.com",hr:"ccprc.com",co:"$40/yr",ds:"32K sq ft skatepark."},{n:"Patriots Point",ad:"40 Patriots Point Rd",ic:"🚢",ur:"https://www.patriotspoint.org",hr:"Daily 9–5",co:"~$30/$20",ds:"USS Yorktown, sub."},{n:"Magnolia Plantation",ad:"3550 Ashley River Rd",ic:"🧚",ur:"https://www.magnoliaplantation.com",hr:"Daily 9–4:30",co:"~$25/$15",ds:"Fairy garden, train, zoo."},{n:"Middleton Place",ad:"4300 Ashley River Rd",ic:"🐴",ur:"https://www.middletonplace.org",hr:"Daily 9–5",co:"~$29/$18",ds:"Farm, stableyards, trails."}];
const BH=[{n:"Isle of Palms County Park",ad:"14th Ave, IOP",ps:"gold",ds:"Best family beach — playground, snack shack, lifeguards.",tp:["🕐 Before 9:30am Sat","💰 $10 or Gold Pass","🛝 Playground","♿ Beach chair","🍔 Snacks"]},{n:"Folly Beach County Park",ad:"1010 W Ashley Ave",ps:"gold",ds:"Lifeguards, showers, rentals. Gentle waves.",tp:["🕐 Before 10am","💰 $10 or Gold Pass","⛱️ Rentals","🚿 Rinse stations","☀️ Bring tent"]},{n:"Kiawah Beachwalker",ad:"8 Beachwalker Dr",ps:"gold",ds:"Pristine, quiet, natural dunes.",tp:["🕐 45 min","💰 $10 or Gold Pass","🧊 Pack cooler","🌿 Boardwalk","📅 Check hours"]},{n:"Sullivan's Island",ad:"Sullivan's Island, SC",ps:"free",ds:"Free. No facilities. Walk to restaurants.",tp:["✨ Free!","🚫 No lifeguards","💧 Bring all","🍽️ Restaurants","👥 Quiet weekdays"]},{n:"Edisto Beach SP",ad:"8377 State Cabin Rd",ps:"state",ds:"Quiet ~1 hr. Trails, camping.",tp:["🕐 1 hour","💰 $8/$5 or Pass","🏕️ Camping","🌲 4-mi trail","🔬 Nature ctr"]},{n:"Hunting Island SP",ad:"2555 Sea Island Pkwy",ps:"state",ds:"Driftwood beach. ~2 hrs.",tp:["🕐 2 hours","💰 $8/$5 or Pass","🪵 Driftwood","🧺 Pack lunch","🐊 Gators"]}];
const LB=[{n:"Main Library",ad:"68 Calhoun St",nt:"Storytimes & crafts."},{n:"Bees Ferry",ad:"3689 Bees Ferry Rd",nt:"Gated outdoor play!"},{n:"Mt. Pleasant",ad:"1133 Mathis Ferry Rd",nt:"Baby storytimes."},{n:"Otranto Road",ad:"2261 Otranto Rd",nt:"Weekly storytimes."},{n:"James Island",ad:"1248 Camp Rd",nt:"Toddler storytimes."},{n:"John's Island",ad:"3531 Maybank Hwy",nt:"Summer reading."},{n:"Hurd/St. Andrews",ad:"1735 N Woodmere Dr",nt:"Newly renovated!"},{n:"Dorchester Rd",ad:"6325 Dorchester Rd",nt:"30+ Storytime Kits."}];
const CM=[{h:"@jetsetchristina",nm:"JetsetChristina",u:"https://www.instagram.com/jetsetchristina/",ds:"Luxury travel & family · 116K",c:"#E8D5B7",i:"JC"},{h:"@chswithkids",nm:"CHS With Kids",u:"https://www.instagram.com/chswithkids/",ds:"Parent recs & weekends",c:"#B5EAD7",i:"CK"},{h:"@charlestontoddlers",nm:"Charleston Toddlers",u:"https://www.instagram.com/charlestontoddlers/",ds:"Toddler activities",c:"#C7CEEA",i:"CT"},{h:"@littlesinthelowcountry",nm:"Littles in the Lowcountry",u:"https://www.instagram.com/littlesinthelowcountry/",ds:"Adventures & gems",c:"#FFD6E0",i:"LL"}];

/* ═══ GOOGLE PLACES PHOTO INTEGRATION ═══ */
// To enable real photos:
// 1. Get a Google Maps API key at console.cloud.google.com
// 2. Enable "Places API" and "Maps JavaScript API"
// 3. Restrict key to charlestonplaygrounds.com
// 4. Add to .env: VITE_GOOGLE_PLACES_KEY=your_key_here
const GKEY=typeof import.meta!=="undefined"&&import.meta.env?.VITE_GOOGLE_PLACES_KEY||"";
const PIDS={3:"ChIJ9Z_RxAB9_ogRQpgniSCkOoo",5:"ChIJoQd6lnl7_ogRARhYCS1fEZE",9:"ChIJzw8vtup7_ogR4FnvI_pwqMY",10:"ChIJBX3NdbBi_ogRJ30r0dak2-8",11:"ChIJs43LHhd5_ogR-mQo-qQXMDQ",12:"ChIJDVQO0x15_ogR8CVS0K3yj48",14:"ChIJw63KiLjX_YgRoMFW5uE_tRE",19:"ChIJk8wpxlF6_ogRsQfHPDOotlc",20:"ChIJs19Aq3N6_ogR9LquDzVhqE0",21:"ChIJbS-NaA96_ogR86R4mF77ymk",22:"ChIJ7Z0GaD16_ogRhZaBSDm1KaE",23:"ChIJLe2Ic0p6_ogRrnl29c3tqt8",24:"ChIJVTpgHABl_ogRWPT_7OQVFO8",25:"ChIJq6pT-qBh_ogR2UScMW3eugc",26:"ChIJzRiTMgpu_ogRUQXSBp2bOLY",27:"ChIJp0YRcYlw_ogRZIR5ZgKLqGM",32:"ChIJy0DeoOlv_ogRR6UfFKnQxCU",33:"ChIJ839Gyhxw_ogROzgaNoyGqEc",35:"ChIJtS4hklFx_ogRTwHFTpkRTEs"};

// Load Google Maps JS API once (adds Places library for photo fetching)
let gMapsLoaded=false;let gMapsLoading=false;let gMapsCallbacks=[];
function loadGMaps(cb){
  if(gMapsLoaded){cb();return;}
  gMapsCallbacks.push(cb);
  if(gMapsLoading)return;
  gMapsLoading=true;
  window._gmcb=()=>{gMapsLoaded=true;gMapsCallbacks.forEach(fn=>fn());gMapsCallbacks=[];};
  const s=document.createElement("script");
  s.src=`https://maps.googleapis.com/maps/api/js?key=${GKEY}&libraries=places&callback=_gmcb`;
  s.async=true;document.head.appendChild(s);
}

// Photo component: uses Google Places JS API, caches in localStorage, falls back to emoji
const PlacePhoto=({id,emoji,hue,height=120,style:sx={}})=>{
  const[src,setSrc]=useState(()=>{try{return localStorage.getItem("cpg_ph_"+id)||null}catch{return null}});
  const pid=PIDS[id];
  useEffect(()=>{
    if(!GKEY||!pid||src)return;
    loadGMaps(()=>{
      const svc=new window.google.maps.places.PlacesService(document.createElement("div"));
      svc.getDetails({placeId:pid,fields:["photos"]},(place,status)=>{
        if(status==="OK"&&place?.photos?.length){
          const url=place.photos[0].getUrl({maxWidth:600,maxHeight:400});
          try{localStorage.setItem("cpg_ph_"+id,url)}catch{}
          setSrc(url);
        }
      });
    });
  },[id,pid,src]);
  if(src)return<div style={{width:"100%",height,backgroundImage:`url(${src})`,backgroundSize:"cover",backgroundPosition:"center",...sx}}/>;
  return<div style={{width:"100%",height,background:`linear-gradient(135deg,hsl(${hue},42%,84%),hsl(${(hue+40)%360},36%,77%))`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:height>150?72:40,...sx}}>{emoji}</div>;
};

/* ═══ UNIFIED DESIGN SYSTEM ═══ */
const CARD={background:$.cd,borderRadius:16,border:`1px solid ${$.b}`,padding:16,width:"100%",boxSizing:"border-box"};
const SECTION_GAP=10; // gap between cards everywhere
const TOP_PAD=16; // space between nav and first content
const Stars=({v,s=13})=><span style={{display:"inline-flex",alignItems:"center",gap:1}}>{[1,2,3,4,5].map(i=><span key={i} style={{fontSize:s,color:v>=i?"#F59E0B":v>=i-.5?"#FCD34D":"#D1D5DB"}}>★</span>)}<span style={{fontSize:Math.max(s*.78,10),fontWeight:700,color:$.m,marginLeft:2}}>{v.toFixed(1)}</span></span>;
const Badge=({children,bg="#E0F2FE",fg="#0369A1"})=><span style={{display:"inline-block",padding:"3px 9px",borderRadius:18,fontSize:10,fontWeight:700,background:bg,color:fg,whiteSpace:"nowrap"}}>{children}</span>;
const gm=a=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(a)}`;
const MapLink=({ad,children})=><a href={gm(ad)} target="_blank" rel="noopener noreferrer" style={{fontSize:11,color:$.p,textDecoration:"none",fontWeight:600}}>{children||`📍 ${ad}`}</a>;
const ExtLink=({href,children})=><a href={href} target="_blank" rel="noopener noreferrer" style={{color:$.p,textDecoration:"none",fontWeight:700}}>{children}</a>;
const PassBadge=({p})=>p==="gold"?<Badge bg="#FEF3C7" fg="#92400E">🏅 Gold Pass</Badge>:p==="state"?<Badge bg="#D1FAE5" fg="#065F46">🌲 State Park</Badge>:p==="free"?<Badge bg="#E0F2FE" fg="#0369A1">✨ Free</Badge>:null;
const ld=(k,d)=>{try{return JSON.parse(localStorage.getItem("cpg_"+k))||d}catch{return d}};
const sv=(k,v)=>{try{localStorage.setItem("cpg_"+k,JSON.stringify(v))}catch{}};
const SectionTitle=({children})=><h2 style={{fontFamily:"'Lilita One',cursive",fontSize:20,color:$.p,margin:`0 0 ${SECTION_GAP}px`}}>{children}</h2>;
const Tip=()=><div style={{textAlign:"center",marginTop:28,paddingTop:14,borderTop:`1px solid ${$.b}`}}><button onClick={()=>document.dispatchEvent(new Event("openTip"))} style={{background:"none",border:`2px solid ${$.a}`,borderRadius:20,padding:"6px 16px",color:$.a,fontWeight:700,fontSize:12,cursor:"pointer",fontFamily:"inherit"}}>📬 Submit a Tip</button></div>;

/* ═══ MODAL STYLES ═══ */
const OV={position:"fixed",inset:0,zIndex:2000,background:"rgba(0,0,0,.4)",display:"flex",alignItems:"center",justifyContent:"center",padding:16};
const MX={background:"white",borderRadius:20,padding:"24px 20px",width:"calc(100% - 32px)",maxWidth:380,boxSizing:"border-box"};
const IN={width:"100%",padding:"10px 12px",borderRadius:8,border:`2px solid ${$.b}`,fontSize:14,marginBottom:7,boxSizing:"border-box",fontFamily:"inherit",outline:"none",color:$.t};

const ContactModal=({x})=>{const[ok,sO]=useState(false);const[tp,sT]=useState("playground");const[nm,sN]=useState("");const[em,sE]=useState("");const[mg,sM]=useState("");const[si,sS]=useState(false);
const go=async()=>{sS(true);try{await fetch("https://formspree.io/f/YOUR_FORM_ID",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:tp,name:nm,email:em,message:mg})})}catch{}sO(true);sS(false)};
if(ok)return<div style={OV} onClick={x}><div onClick={e=>e.stopPropagation()} style={{...MX,textAlign:"center"}}><div style={{fontSize:44}}>✅</div><p style={{fontWeight:700,margin:"8px 0"}}>Thanks!</p><button onClick={x} style={{padding:"8px 18px",borderRadius:10,background:$.a,color:"white",border:"none",fontWeight:700,cursor:"pointer",fontFamily:"inherit"}}>Close</button></div></div>;
return<div style={OV} onClick={x}><div onClick={e=>e.stopPropagation()} style={{...MX,maxHeight:"85vh",overflowY:"auto"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:8}}><b style={{fontFamily:"'Lilita One',cursive",color:$.p}}>📬 Tip</b><button onClick={x} style={{background:"none",border:"none",fontSize:16,cursor:"pointer"}}>✕</button></div>
<div style={{display:"flex",gap:4,marginBottom:8,flexWrap:"wrap"}}>{[["playground","🛝"],["tip","💡"],["restaurant","🍽️"],["other","💬"]].map(([v,l])=><button key={v} onClick={()=>sT(v)} style={{padding:"4px 10px",borderRadius:14,border:`2px solid ${tp===v?$.a:$.b}`,background:tp===v?$.al:"white",color:tp===v?$.a:$.m,fontWeight:700,fontSize:11,cursor:"pointer",fontFamily:"inherit"}}>{l}</button>)}</div>
<input value={nm} onChange={e=>sN(e.target.value)} placeholder="Name" style={IN}/><input value={em} onChange={e=>sE(e.target.value)} placeholder="Email (opt)" style={IN}/><textarea value={mg} onChange={e=>sM(e.target.value)} placeholder="Tell us..." rows={3} style={{...IN,resize:"vertical"}}/><button onClick={go} disabled={!mg.trim()||si} style={{width:"100%",padding:"11px",borderRadius:10,background:mg.trim()?$.a:"#ccc",color:"white",border:"none",fontSize:14,fontWeight:800,cursor:mg.trim()?"pointer":"not-allowed",fontFamily:"inherit"}}>{si?"...":"Submit →"}</button></div></div>};

const AuthModal=({x,au})=>{const[e,sE]=useState("");const[n,sN]=useState("");const[ok,sO]=useState(false);
return<div style={OV} onClick={x}><div onClick={ev=>ev.stopPropagation()} style={MX}><div style={{fontSize:36,textAlign:"center"}}>🛝</div><h2 style={{fontFamily:"'Lilita One',cursive",fontSize:18,color:$.p,textAlign:"center",margin:"4px 0 12px"}}>Join!</h2><input value={n} onChange={ev=>sN(ev.target.value)} placeholder="Name" style={IN}/><input value={e} onChange={ev=>sE(ev.target.value)} placeholder="Email" type="email" style={IN}/><label style={{display:"flex",gap:6,alignItems:"flex-start",margin:"2px 0 10px"}}><input type="checkbox" checked={ok} onChange={ev=>sO(ev.target.checked)} style={{marginTop:2,width:15,height:15,accentColor:$.p}}/><span style={{fontSize:11,color:$.m}}>OK to email updates. Never spam.</span></label><button onClick={()=>{if(e.includes("@")&&ok)au({name:n,email:e})}} disabled={!e.includes("@")||!ok} style={{width:"100%",padding:"12px",borderRadius:10,background:(e.includes("@")&&ok)?$.a:"#ccc",color:"white",border:"none",fontSize:15,fontWeight:800,cursor:(e.includes("@")&&ok)?"pointer":"not-allowed",fontFamily:"inherit"}}>Go! 🎉</button><button onClick={x} style={{width:"100%",marginTop:4,padding:"6px",background:"none",border:"none",color:$.m,fontSize:12,cursor:"pointer",fontFamily:"inherit"}}>Just browsing</button></div></div>};

/* ═══ MAIN APP ═══ */
export default function App(){
const[vw,sV]=useState("playgrounds");const[ar,sA]=useState("All");const[tg,sTg]=useState([]);const[so,sS]=useState("overall");const[sr,sSr]=useState("");const[dt,sD]=useState(null);const[fv,sFv]=useState(()=>ld("fv",[]));const[bk,sBk]=useState(()=>ld("bk",[]));const[vi,sVi]=useState(()=>ld("vi",[]));const[sp,sSp]=useState(false);const[us,sUs]=useState(()=>ld("us",null));const[sa,sSa]=useState(false);const[sc,sSc]=useState(false);const[ur,sUr]=useState(()=>ld("ur",{}));const[ed,sEd]=useState(false);
useEffect(()=>sv("fv",fv),[fv]);useEffect(()=>sv("bk",bk),[bk]);useEffect(()=>sv("vi",vi),[vi]);useEffect(()=>sv("us",us),[us]);useEffect(()=>sv("ur",ur),[ur]);
useEffect(()=>{const h=()=>sSc(true);document.addEventListener("openTip",h);return()=>document.removeEventListener("openTip",h)},[]);
const gd=useCallback(fn=>(...a)=>{if(!us){sSa(true);return}fn(...a)},[us]);
const tF=gd(id=>sFv(p=>p.includes(id)?p.filter(x=>x!==id):[...p,id]));
const tB=gd(id=>sBk(p=>p.includes(id)?p.filter(x=>x!==id):[...p,id]));
const tV=gd(id=>sVi(p=>p.includes(id)?p.filter(x=>x!==id):[...p,id]));
const fl=useMemo(()=>{let r=PG;if(ar!=="All")r=r.filter(p=>p.a===ar);if(tg.length)r=r.filter(p=>tg.every(t=>p.t.includes(t)));if(sr){const s=sr.toLowerCase();r=r.filter(p=>p.n.toLowerCase().includes(s)||p.d.toLowerCase().includes(s)||p.a.toLowerCase().includes(s))}return[...r].sort((a,b)=>(b.r[so]||0)-(a.r[so]||0))},[ar,tg,sr,so]);

return(
<div style={{width:"100%",minHeight:"100vh",background:$.bg,fontFamily:"'Nunito',sans-serif",color:$.t}}>
<style>{`@import url('https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700;800;900&family=Lilita+One&display=swap');*{box-sizing:border-box;-webkit-tap-highlight-color:transparent;margin:0}html{overflow-y:scroll}html,body{overflow-x:hidden;margin:0;padding:0;font-family:'Nunito',sans-serif;background:${$.bg}}select,option{color:${$.t}!important;background:white!important}input::placeholder,textarea::placeholder{color:#999!important;opacity:1!important}
@media(max-width:600px){.mob-col{flex-direction:column!important}.mob-full{width:100%!important;height:160px!important}.mob-1{grid-template-columns:1fr!important}}`}</style>
{sa&&<AuthModal x={()=>sSa(false)} au={u=>{sUs(u);sSa(false)}}/>}{sc&&<ContactModal x={()=>sSc(false)}/>}

{/* ═══ SINGLE FIXED COLUMN — EVERYTHING INSIDE ═══ */}
<div style={{width:"100%",maxWidth:700,margin:"0 auto",padding:"0 14px",display:"flex",flexDirection:"column",minHeight:"100vh"}}>

{/* HEADER */}
<div style={{background:`linear-gradient(135deg,${$.p},#40916C,${$.pd})`,color:"white",padding:"12px 14px",borderRadius:"0 0 14px 14px"}}>
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}>
<div style={{cursor:"pointer"}} onClick={()=>{sV("playgrounds");sD(null)}}><h1 style={{fontFamily:"'Lilita One',cursive",fontSize:19,margin:0}}>🛝 Charleston Playgrounds</h1><p style={{fontSize:10,opacity:.85,margin:"2px 0 0",fontWeight:600}}>35 playgrounds ✦ rated & reviewed ✦ 2026</p></div>
<div style={{display:"flex",gap:4}}><button onClick={()=>sSc(true)} style={{background:"rgba(255,255,255,.2)",border:"none",borderRadius:8,padding:"5px 9px",color:"white",fontSize:11,fontWeight:700,cursor:"pointer",fontFamily:"inherit"}}>📬</button><button onClick={()=>us?sSp(!sp):sSa(true)} style={{background:"rgba(255,255,255,.2)",border:"none",borderRadius:8,padding:"5px 9px",color:"white",fontSize:11,fontWeight:700,cursor:"pointer",fontFamily:"inherit"}}>{us?`👋 ${us.name||"Me"}`:"Sign In"}</button></div>
</div></div>

{/* NAV */}
<div style={{background:$.cd,border:`1px solid ${$.b}`,borderTop:"none",borderRadius:"0 0 10px 10px",display:"flex",overflowX:"auto",position:"sticky",top:0,zIndex:100,marginBottom:TOP_PAD}}>
{[["playgrounds","Playgrounds","🛝"],["activities","Activities","🎪"],["beaches","Beaches","🏖️"],["libraries","Libraries","📚"],["passes","Passes","🎫"],["community","Community","💬"]].map(([k,l,i])=><button key={k} onClick={()=>{sV(k);sD(null)}} style={{flex:"1 0 auto",padding:"10px 5px",border:"none",background:"none",cursor:"pointer",fontFamily:"inherit",fontSize:10,fontWeight:vw===k?800:600,color:vw===k?$.p:$.m,borderBottom:vw===k?`3px solid ${$.a}`:"3px solid transparent",whiteSpace:"nowrap"}}>{i} {l}</button>)}
</div>

{/* DASHBOARD */}
{sp&&us&&<div style={{...CARD,marginBottom:SECTION_GAP,background:$.w}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:6}}><b style={{fontFamily:"'Lilita One',cursive",fontSize:15,color:$.p}}>🎒 Dashboard</b><div><button onClick={()=>{sUs(null);sSp(false);sv("us",null)}} style={{background:"none",border:"none",color:$.m,fontSize:10,cursor:"pointer",fontFamily:"inherit"}}>Log Out</button> <button onClick={()=>sEd(!ed)} style={{fontSize:10,cursor:"pointer",fontFamily:"inherit",background:"none",border:`1px solid ${$.p}`,borderRadius:5,padding:"1px 6px",color:$.p,fontWeight:700}}>✏️</button> <button onClick={()=>sSp(false)} style={{background:"none",border:"none",fontSize:13,cursor:"pointer"}}>✕</button></div></div><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:5}} className="mob-1">{[["Fav",fv.length,"❤️","#FEE2E2"],["List",bk.length,"🪣","#DBEAFE"],["Done",vi.length,"✅","#D1FAE5"],["Rate",Object.keys(ur).length,"⭐","#FEF3C7"]].map(([l,v,i,c])=><div key={l} style={{background:c,borderRadius:8,padding:6,textAlign:"center"}}><div style={{fontSize:14}}>{i} <b>{v}</b></div><div style={{fontSize:9,color:$.m}}>{l}</div></div>)}</div>{ed&&<div style={{marginTop:6,padding:8,background:$.cd,borderRadius:8,border:`2px solid ${$.a}`}}><input defaultValue={us.name} id="pn" placeholder="Name" style={IN}/><input defaultValue={us.email} id="pe" placeholder="Email" style={IN}/><button onClick={()=>{sUs({...us,name:document.getElementById("pn").value,email:document.getElementById("pe").value});sEd(false)}} style={{padding:"5px 12px",borderRadius:6,background:$.p,color:"white",border:"none",fontWeight:700,fontSize:11,cursor:"pointer",fontFamily:"inherit"}}>Save</button></div>}</div>}

{/* ═══ CONTENT — flex:1 fills remaining space ═══ */}
<div style={{flex:1}}>

{/* PLAYGROUNDS LIST */}
{vw==="playgrounds"&&!dt&&<div>
<input value={sr} onChange={e=>sSr(e.target.value)} placeholder="🔍  Search 35 playgrounds..." style={{...IN,borderRadius:20,fontSize:14,padding:"11px 16px",marginBottom:SECTION_GAP,background:$.cd}}/>
<div style={{display:"flex",gap:5,overflowX:"auto",marginBottom:8,paddingBottom:3}}>{AR.map(a=><button key={a} onClick={()=>sA(a)} style={{padding:"6px 12px",borderRadius:18,border:"none",cursor:"pointer",background:ar===a?$.a:$.cd,color:ar===a?"white":$.t,fontWeight:700,fontSize:11,fontFamily:"inherit",flexShrink:0}}>{a}</button>)}</div>
<div style={{display:"flex",flexWrap:"wrap",gap:3,marginBottom:8}}>{Object.entries(TG).map(([k,l])=><button key={k} onClick={()=>sTg(p=>p.includes(k)?p.filter(x=>x!==k):[...p,k])} style={{padding:"3px 8px",borderRadius:12,cursor:"pointer",border:tg.includes(k)?`2px solid ${$.a}`:"2px solid transparent",background:tg.includes(k)?$.al:"#EFEDE8",color:tg.includes(k)?$.a:$.m,fontWeight:600,fontSize:10,fontFamily:"inherit"}}>{l}</button>)}</div>
<div style={{display:"flex",alignItems:"center",gap:6,marginBottom:SECTION_GAP}}><select value={so} onChange={e=>sS(e.target.value)} style={{padding:"4px 8px",borderRadius:8,border:`1px solid ${$.b}`,fontSize:11,fontFamily:"inherit",background:"white",color:$.t}}>{RC.map(c=><option key={c.k} value={c.k}>{c.i} {c.l}</option>)}</select><span style={{marginLeft:"auto",fontSize:11,fontWeight:700,color:$.m}}>{fl.length} results</span></div>
{fl.map(pg=><div key={pg.id} onClick={()=>sD(pg)} style={{...CARD,marginBottom:SECTION_GAP,padding:0,overflow:"hidden",cursor:"pointer"}}><div className="mob-col" style={{display:"flex"}}><div className="mob-full" style={{width:110,minHeight:100,flexShrink:0,overflow:"hidden"}}><PlacePhoto id={pg.id} emoji={pg.e} hue={pg.h} height={200} style={{minHeight:"100%"}}/></div><div style={{padding:"10px 12px",flex:1,minWidth:0}}><h3 style={{margin:0,fontSize:14,fontWeight:800}}>{pg.n}</h3><MapLink ad={pg.ad}>📍 {pg.a}</MapLink>{pg.r.overall>0?<div style={{margin:"3px 0"}}><Stars v={pg.r.overall}/></div>:<div style={{margin:"3px 0",fontSize:10,color:$.a,fontWeight:700}}>🆕 Rate me!</div>}<p style={{margin:0,fontSize:11,color:"#666",lineHeight:1.35,display:"-webkit-box",WebkitLineClamp:2,WebkitBoxOrient:"vertical",overflow:"hidden"}}>{pg.d}</p><div style={{display:"flex",flexWrap:"wrap",gap:3,marginTop:3}}>{pg.p&&<PassBadge p={pg.p}/>}{pg.t.slice(0,3).map(t=><Badge key={t}>{TG[t]}</Badge>)}{pg.t.length>3&&<Badge bg="#EFEDE8" fg={$.m}>+{pg.t.length-3}</Badge>}</div></div></div></div>)}
{!fl.length&&<div style={{textAlign:"center",padding:30,color:$.m}}>🔍 No matches</div>}
<Tip/></div>}

{/* DETAIL */}
{vw==="playgrounds"&&dt&&(()=>{const p=dt;return<div><button onClick={()=>sD(null)} style={{background:"none",border:"none",cursor:"pointer",fontFamily:"inherit",fontSize:13,fontWeight:700,color:$.p,padding:0,marginBottom:SECTION_GAP}}>← Back</button><div style={{...CARD,padding:0,overflow:"hidden"}}><PlacePhoto id={p.id} emoji={p.e} hue={p.h} height={220}/><div style={{padding:16}}><h2 style={{fontFamily:"'Lilita One',cursive",fontSize:20,color:$.p,margin:"0 0 3px"}}>{p.n}</h2><MapLink ad={p.ad}/><div style={{display:"flex",flexWrap:"wrap",gap:5,margin:"10px 0"}}><button onClick={()=>tF(p.id)} style={{padding:"7px 12px",borderRadius:10,border:`2px solid ${fv.includes(p.id)?"#EF4444":$.b}`,background:fv.includes(p.id)?"#FEE2E2":$.cd,cursor:"pointer",fontFamily:"inherit",fontWeight:700,fontSize:12,color:$.t}}>{fv.includes(p.id)?"❤️ Fav'd":"🤍 Fav"}</button><button onClick={()=>tB(p.id)} style={{padding:"7px 12px",borderRadius:10,border:`2px solid ${bk.includes(p.id)?$.od:$.b}`,background:bk.includes(p.id)?$.o:$.cd,cursor:"pointer",fontFamily:"inherit",fontWeight:700,fontSize:12,color:$.t}}>{bk.includes(p.id)?"🪣 Listed":"🪣 Add"}</button><button onClick={()=>tV(p.id)} style={{padding:"7px 12px",borderRadius:10,border:`2px solid ${vi.includes(p.id)?"#059669":$.b}`,background:vi.includes(p.id)?"#D1FAE5":$.cd,cursor:"pointer",fontFamily:"inherit",fontWeight:700,fontSize:12,color:$.t}}>{vi.includes(p.id)?"✅ Done":"☐ Visit"}</button></div><p style={{fontSize:13,lineHeight:1.6,color:"#444",margin:"0 0 12px"}}>{p.d}</p>{p.p&&<div style={{marginBottom:8}}><PassBadge p={p.p}/></div>}<div style={{display:"flex",flexWrap:"wrap",gap:3,marginBottom:14}}>{p.t.map(t=><Badge key={t}>{TG[t]}</Badge>)}</div>
{p.r.overall>0&&<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(145px,1fr))",gap:4,marginBottom:12}} className="mob-1">{RC.map(c=><div key={c.k} style={{background:"#F5F3EE",borderRadius:8,padding:"6px 8px",display:"flex",justifyContent:"space-between",alignItems:"center"}}><span style={{fontSize:10,fontWeight:700}}>{c.i} {c.l}</span><Stars v={p.r[c.k]||0} s={10}/></div>)}</div>}
<div style={{background:$.w,borderRadius:10,padding:10,marginBottom:12}}><b style={{fontSize:12}}>⭐ Rate</b><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(145px,1fr))",gap:3,marginTop:4}} className="mob-1">{RC.map(c=><div key={c.k} style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><span style={{fontSize:10,fontWeight:600}}>{c.i} {c.l}</span><div>{[1,2,3,4,5].map(x=><button key={x} onClick={gd(()=>sUr(prev=>({...prev,[`${p.id}-${c.k}`]:x})))} style={{background:"none",border:"none",fontSize:16,cursor:"pointer",padding:"0 1px",color:(ur[`${p.id}-${c.k}`]||0)>=x?"#F59E0B":"#D1D5DB"}}>★</button>)}</div></div>)}</div></div>
{p.f?.length>0&&<div style={{marginBottom:12}}><b style={{fontSize:13,color:$.p}}>🍽️ Eats</b>{p.f.map((r,i)=><a key={i} href={gm(r.a)} target="_blank" rel="noopener noreferrer" style={{display:"block",background:"#F5F3EE",borderRadius:8,padding:"8px 10px",textDecoration:"none",color:$.t,border:`1px solid ${$.b}`,marginTop:4}}><b style={{fontSize:13}}>{r.n}</b> <Badge bg={$.pl} fg={$.p}>{r.t}</Badge><br/><span style={{fontSize:11,color:$.m}}>{r.d} · 📍 {r.a}</span></a>)}</div>}
<a href={gm(p.ad)} target="_blank" rel="noopener noreferrer" style={{display:"inline-block",padding:"10px 18px",background:$.a,color:"white",borderRadius:12,textDecoration:"none",fontWeight:800,fontSize:13,fontFamily:"inherit"}}>📍 Directions</a></div></div><Tip/></div>})()}

{/* ACTIVITIES — same CARD style */}
{vw==="activities"&&<div><SectionTitle>🎪 Things to Do</SectionTitle>{AC.map((a,i)=><div key={i} style={{...CARD,marginBottom:SECTION_GAP}}><div style={{display:"flex",gap:10,alignItems:"flex-start"}}><div style={{fontSize:22,width:36,height:36,display:"flex",alignItems:"center",justifyContent:"center",background:"#F5F3EE",borderRadius:10,flexShrink:0}}>{a.ic}</div><div style={{flex:1,minWidth:0}}><ExtLink href={a.ur}><span style={{fontSize:14,fontWeight:800,color:$.t}}>{a.n} ↗</span></ExtLink><br/><MapLink ad={a.ad}/><p style={{margin:"3px 0",fontSize:12,color:"#555",lineHeight:1.35}}>{a.ds}</p><div style={{fontSize:11,color:$.p,fontWeight:700}}>🕐 {a.hr} · 💰 {a.co}</div></div></div></div>)}<Tip/></div>}

{/* BEACHES */}
{vw==="beaches"&&<div><SectionTitle>🏖️ Beaches</SectionTitle>{BH.map((b,i)=><div key={i} style={{...CARD,marginBottom:SECTION_GAP}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",flexWrap:"wrap",gap:4,marginBottom:4}}><div><h3 style={{margin:0,fontSize:15,fontWeight:800}}>{b.n}</h3><MapLink ad={b.ad}/></div><PassBadge p={b.ps}/></div><p style={{fontSize:12,lineHeight:1.5,color:"#444",margin:"0 0 6px"}}>{b.ds}</p><div style={{background:"#F5F3EE",borderRadius:10,padding:"8px 10px"}}>{b.tp.map((t,j)=><div key={j} style={{fontSize:11,lineHeight:1.5,color:"#444"}}>{t}</div>)}</div></div>)}<Tip/></div>}

{/* LIBRARIES */}
{vw==="libraries"&&<div><SectionTitle>📚 Storytimes</SectionTitle><div style={{...CARD,background:$.pl,marginBottom:SECTION_GAP}}><span style={{fontSize:12,fontWeight:600}}>💡 Ask about Storytime Kits & Explore with CCPL for free passes!</span></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(240px,1fr))",gap:SECTION_GAP}} className="mob-1">{LB.map((l,i)=><div key={i} style={CARD}><h3 style={{margin:"0 0 2px",fontSize:13,fontWeight:800}}>📚 {l.n}</h3><MapLink ad={l.ad}/><p style={{margin:"3px 0 0",fontSize:12,color:"#555"}}>{l.nt}</p></div>)}</div><Tip/></div>}

{/* PASSES — same CARD wrapper, accent via left border */}
{vw==="passes"&&<div><SectionTitle>🎫 Passes 2026</SectionTitle>
<div style={{...CARD,marginBottom:SECTION_GAP,borderLeft:`4px solid #F59E0B`,background:"#FFFEF5"}}><h3 style={{margin:0,fontSize:16,fontWeight:900,color:"#78350F"}}>🏅 Gold Pass — $99 ($84 res)</h3><p style={{fontSize:11,lineHeight:1.7,color:"#78350F",margin:"3px 0"}}><b>Parks:</b> James Is · Palmetto Is · Wannamaker · Caw Caw · Johns Is · McLeod · Laurel Hill · Lighthouse Inlet · Meggett · Stono River<br/><b>Beaches:</b> Folly · IOP · Kiawah · <b>Events:</b> Harvest · Lights · Cajun · Reggae</p><ExtLink href="https://www.ccprc.com/16/Park-Passes"><span style={{color:"#78350F",fontSize:12}}>Buy →</span></ExtLink></div>
<div style={{...CARD,marginBottom:SECTION_GAP,borderLeft:`4px solid #059669`,background:"#F0FDF4"}}><h3 style={{margin:0,fontSize:16,fontWeight:900,color:"#064E3B"}}>🌲 State Park — $99</h3><p style={{fontSize:11,lineHeight:1.7,color:"#064E3B",margin:"3px 0"}}><b>Near CHS:</b> Charles Towne 15m · Dorchester 20m · Givhans 45m · Edisto 1h<br/><b>Beaches:</b> Edisto 1h · Hunting Is 2h · Huntington 2h</p><ExtLink href="https://southcarolinaparks.com"><span style={{color:"#064E3B",fontSize:12}}>Buy →</span></ExtLink></div>
<div style={{...CARD,marginBottom:SECTION_GAP,borderLeft:`4px solid #0284C7`,background:"#F0F9FF"}}><h3 style={{margin:0,fontSize:16,fontWeight:900,color:"#0C4A6E"}}>📚 CCPL — Free!</h3><p style={{fontSize:12,color:"#0C4A6E",margin:"3px 0"}}>Borrow: Aquarium, Museum, Gibbes, Parks, Gold Pass!</p><ExtLink href="https://www.ccpl.org"><span style={{color:"#0C4A6E",fontSize:12}}>CCPL →</span></ExtLink></div>
<div style={{...CARD,marginBottom:SECTION_GAP}}><h3 style={{margin:0,fontSize:16,fontWeight:900}}>🐠 Aquarium</h3><p style={{fontSize:11,color:"#555",margin:"3px 0",lineHeight:1.6}}><b>Day:</b> ~$30-45 · <b>Adult:</b> $99/yr · <b>Family:</b> $249 · <b>Family+:</b> $319 · <b>Angelfish:</b> $40 · Military 15% · Teachers free · Gold Pass $15 off</p><ExtLink href="https://scaquarium.org/membership/"><span style={{fontSize:11}}>Details →</span></ExtLink></div>
<div style={{...CARD,marginBottom:SECTION_GAP}}><h3 style={{margin:0,fontSize:16,fontWeight:900}}>🎨 Children's Museum</h3><p style={{fontSize:11,color:"#555",margin:"3px 0",lineHeight:1.6}}><b>Day:</b> $15/$13/$3 · M-Sa 10-5, Su 12-5 · Members 9am · SuperStars Sun FREE · Quarter Day 25¢!</p><ExtLink href="https://explorecml.org/visit/"><span style={{fontSize:11}}>Visit →</span></ExtLink></div>
<div style={{...CARD}}><h3 style={{margin:0,fontSize:16,fontWeight:900}}>🌊 Splash Pass — ~$100+</h3><p style={{fontSize:11,color:"#555",margin:"3px 0"}}>Seasonal. Whirlin' Waters, Splash Zone, Splash Island.</p><ExtLink href="https://www.ccprc.com/16/Park-Passes"><span style={{fontSize:11}}>Buy →</span></ExtLink></div>
<Tip/></div>}

{/* COMMUNITY — same CARD style */}
{vw==="community"&&<div><SectionTitle>💬 Community</SectionTitle>{CM.map(c=><a key={c.h} href={c.u} target="_blank" rel="noopener noreferrer" style={{...CARD,display:"flex",gap:10,alignItems:"center",marginBottom:SECTION_GAP,textDecoration:"none",color:$.t,padding:14}}><div style={{width:44,height:44,borderRadius:44,padding:2,background:"linear-gradient(45deg,#f09433,#e6683c,#dc2743,#cc2366,#bc1888)",flexShrink:0}}><div style={{width:40,height:40,borderRadius:40,background:c.c,display:"flex",alignItems:"center",justifyContent:"center"}}><span style={{fontWeight:900,fontSize:14,color:"#444",fontFamily:"'Lilita One',cursive"}}>{c.i}</span></div></div><div style={{minWidth:0}}><div style={{fontWeight:800,fontSize:14}}>{c.nm}</div><div style={{fontSize:11,color:$.a,fontWeight:700}}>{c.h}</div><div style={{fontSize:11,color:$.m}}>{c.ds}</div></div></a>)}
<h3 style={{fontFamily:"'Lilita One',cursive",fontSize:15,color:$.p,margin:`12px 0 ${SECTION_GAP}px`}}>Resources</h3><div style={{display:"grid",gridTemplateColumns:"repeat(2,1fr)",gap:SECTION_GAP}} className="mob-1">{[["Kidding Around CHS","Events","https://kiddingaroundcharleston.com","🎉"],["Charleston Moms","Guides","https://charlestonmoms.com","👩‍👧‍👦"],["Lowcountry Parent","News","https://www.postandcourier.com/lowcountryparent/","📰"],["CCPL Events","Storytimes","https://ccplsc.libcal.com/calendar","📅"]].map(([n,d,u,i])=><a key={n} href={u} target="_blank" rel="noopener noreferrer" style={{...CARD,textDecoration:"none",color:$.t,padding:10}}><div style={{fontSize:16,marginBottom:1}}>{i}</div><div style={{fontWeight:800,fontSize:11}}>{n}</div><div style={{fontSize:10,color:$.m}}>{d}</div></a>)}</div><Tip/></div>}

</div>{/* end content */}

{/* FOOTER */}
<div style={{background:$.pd,color:"rgba(255,255,255,.7)",textAlign:"center",padding:"14px",fontSize:10,borderRadius:"12px 12px 0 0",marginTop:16}}><div style={{fontFamily:"'Lilita One',cursive",fontSize:13,color:"white"}}>🛝 charlestonplaygrounds.com</div><p style={{margin:0}}>35 playgrounds · March 2026</p></div>

</div>{/* end single column */}
</div>);}
